(function(w){
'use strict';
var active=null;
function t(ru,uk){return w.ZargotaI18n&&w.ZargotaI18n.getLocale()==='uk'?uk:ru;}
function local(v,key){return w.ZargotaI18n&&w.ZargotaI18n.getLocale()==='uk'&&v[key+'Uk']||v[key]||'';}
function el(tag,text){var e=document.createElement(tag);if(text!=null)e.textContent=text;return e;}
function settings(project){return Object.assign({enabled:false,place:'',placeUk:'',title:project.title||'',titleUk:project.titleUk||'',time:'',timeUk:'',titleMs:2200,revealMs:2600,sound:true,soundUrl:''},project.intro||{});}
function sample(progress){var p=Math.max(0,Math.min(1,progress)),ease=p*p*(3-2*p);return{scale:.85+.15*ease,lift:(1-ease)*.045,opacity:1-ease};}
function cancel(){if(active)active.stop(false);}
function play(project,host,draw,done){
 cancel();var cfg=settings(project);if(!cfg.enabled){draw(1);done();return;}
 var layer=el('section');layer.className='zg-episode-intro';layer.setAttribute('aria-label',t('Заставка эпизода','Заставка епізоду'));layer.tabIndex=-1;var veil=el('div');veil.className='zg-intro-veil';var title=el('div');title.className='zg-intro-title';title.setAttribute('aria-live','polite');var small=el('small'),heading=el('h1');title.append(small,heading);var skip=el('button',t('Пропустить заставку','Пропустити заставку'));skip.type='button';skip.className='zg-intro-skip';layer.append(veil,title,skip);host.appendChild(layer);host.classList.add('has-episode-intro');
 var raf=0,context=null,track=null,stopped=false,stage=-1,began=0,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,hold=Math.max(800,Math.min(6000,Number(cfg.titleMs)||2200)),reveal=Math.max(400,Math.min(8000,Number(cfg.revealMs)||2600));var cards=[{label:t('Место','Місце'),text:local(cfg,'place')},{label:t('Эпизод','Епізод'),text:local(cfg,'title')},{label:t('Время','Час'),text:local(cfg,'time')}].filter(function(c){return c.text.trim();});
 function stop(complete){if(stopped)return;stopped=true;cancelAnimationFrame(raf);if(track){track.pause();track.src='';}if(context)context.close().catch(function(){});layer.remove();host.classList.remove('has-episode-intro');if(active&&active.layer===layer)active=null;if(complete){draw(1);done();}}
 active={layer:layer,stop:stop};skip.onclick=function(){stop(true);};layer.onkeydown=function(e){if(e.key==='Escape'){e.preventDefault();e.stopPropagation();stop(true);}};
 function cue(){if(!cfg.sound)return;if(cfg.soundUrl){if(track)track.pause();track=new Audio(cfg.soundUrl);track.volume=.35;track.play().catch(function(){});return;}if(!context)return;var now=context.currentTime;[146.83,220,293.66].forEach(function(f,i){var osc=context.createOscillator(),gain=context.createGain();osc.type='sine';osc.frequency.value=f;gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.026/(i+1),now+.12);gain.gain.exponentialRampToValueAtTime(.0001,now+1.4);osc.connect(gain);gain.connect(context.destination);osc.start(now);osc.stop(now+1.5);});}
 function tick(now){if(stopped)return;var elapsed=now-began,index=Math.floor(elapsed/hold);if(index<cards.length){if(index!==stage){stage=index;small.textContent=cards[index].label;heading.textContent=cards[index].text;cue();}var fraction=(elapsed%hold)/hold;title.style.opacity=String(Math.min(1,fraction/.22,(1-fraction)/.22));}else{title.style.opacity='0';var progress=Math.min(1,(elapsed-cards.length*hold)/reveal);veil.style.opacity=String(sample(progress).opacity);draw(reduced?1:progress);if(progress===1){stop(true);return;}}raf=requestAnimationFrame(tick);}
 function begin(){if(stopped)return;var start=layer.querySelector('.zg-intro-start');if(start)start.remove();if(cfg.sound&&!cfg.soundUrl){try{context=new (w.AudioContext||w.webkitAudioContext)();context.resume().catch(function(){});}catch(ignore){}}draw(reduced?1:0);began=performance.now();raf=requestAnimationFrame(tick);layer.focus();}
 if(navigator.userActivation&&navigator.userActivation.isActive)begin();else{var start=el('button',t('▶ Начать эпизод','▶ Почати епізод'));start.type='button';start.className='zg-intro-start';start.onclick=begin;layer.appendChild(start);start.focus();draw(reduced?1:0);}
}
function preview(project,onDone){var screen=el('div');screen.className='zg-intro-preview';var scene=((project.scenes||[]).find(function(s){return s.id===project.startSceneId;})||{}).scene||project.scene||{},world=el('div');world.className='zg-intro-preview-world';var img=el('img');img.src=(scene.layers||[])[0]?.image||'';img.alt='';world.appendChild(img);screen.appendChild(world);document.body.appendChild(screen);var token=(scene.tokens||[]).find(function(v){return v.id===project.heroTokenId;});if(token){var dot=el('img');dot.className='zg-intro-preview-token';dot.src=token.image;dot.style.left=token.x+'%';dot.style.top=token.y+'%';world.appendChild(dot);}var copy=Object.assign({},project,{intro:Object.assign({},settings(project),{enabled:true})});play(copy,screen,function(progress){var width=(scene.boardWidth||24)*(scene.gridSize||64),height=(scene.boardHeight||16)*(scene.gridSize||64),z=(scene.story||{}).cameraZoom||1,c=w.ZargotaStoryCamera.layout(innerWidth,innerHeight,width,height,z,0,0),x=token?(50-token.x)/100*width*c.scale:0,y=token?(50-token.y)/100*height*c.scale:0;c=w.ZargotaStoryCamera.layout(innerWidth,innerHeight,width,height,z,x,y);var frame=sample(progress);world.style.width=width+'px';world.style.height=height+'px';world.style.transform='translate(calc(-50% + '+c.x+'px),calc(-50% + '+(c.y-innerHeight*frame.lift)+'px)) scale('+(c.scale*frame.scale)+')';},function(){screen.remove();if(onDone)onDone();});}
function edit(project,save){var old=document.getElementById('zg-intro-settings');if(old)old.remove();var d=el('dialog');d.id='zg-intro-settings';d.className='zg-custom-menu zg-intro-settings';var cfg=settings(project);d.appendChild(el('h2',t('Заставка эпизода','Заставка епізоду')));var form=el('form');form.method='dialog';d.appendChild(form);
 function field(label,key,type){var l=el('label',label),i=el('input');i.type=type||'text';if(type==='checkbox')i.checked=!!cfg[key];else i.value=cfg[key];i.oninput=function(){cfg[key]=type==='checkbox'?i.checked:type==='number'?Number(i.value):i.value;};l.appendChild(i);form.appendChild(l);return i;}
 field(t('Включить заставку','Увімкнути заставку'),'enabled','checkbox');[['place','Место','Місце'],['title','Название эпизода','Назва епізоду'],['time','Время · необязательно','Час · необов’язково']].forEach(function(p){var row=el('div');row.className='zg-intro-locale-row';form.appendChild(row);var ru=field(p[1]+' · RU',p[0]),uk=field(p[2]+' · UA',p[0]+'Uk');row.append(ru.parentNode,uk.parentNode);});
 field(t('Длительность титра, мс','Тривалість титру, мс'),'titleMs','number').min=800;field(t('Проявление и приближение, мс','Поява й наближення, мс'),'revealMs','number').min=400;field(t('Звук при появлении надписи','Звук під час появи напису'),'sound','checkbox');var source=field(t('Свой звук · пусто — мягкий аккорд','Власний звук · порожньо — м’який акорд'),'soundUrl');if(w.ZargotaStoryAssets)w.ZargotaStoryAssets.attach(source,'audio');form.appendChild(el('p',t('Камера плавно приближается с 85% до настроенного масштаба и направляется к герою.','Камера плавно наближається з 85% до налаштованого масштабу й прямує до героя.')));var watch=el('button',t('▶ Предпросмотр','▶ Попередній перегляд'));watch.type='button';watch.onclick=function(){d.close();preview(Object.assign({},project,{intro:cfg}),function(){d.showModal();});};var apply=el('button',t('Сохранить','Зберегти'));apply.type='submit';var close=el('button',t('Отмена','Скасувати'));close.type='button';close.onclick=function(){d.remove();};form.append(watch,apply,close);form.onsubmit=function(e){e.preventDefault();save(function(p){p.intro=cfg;});d.remove();};d.addEventListener('cancel',function(){d.remove();});document.body.appendChild(d);d.showModal();}
w.ZargotaStoryIntro={settings:settings,sample:sample,play:play,cancel:cancel,edit:edit,preview:preview};
})(window);
