(function(w){
 'use strict';
 function t(ru,uk){return w.ZargotaI18n&&w.ZargotaI18n.getLocale()==='uk'?uk:ru;}
 var menu=null;
 function close(){if(menu){menu.remove();menu=null;}}
 function open(select){close();var panel=document.createElement('dialog');panel.className='zg-custom-menu';menu=panel;var title=document.createElement('header');title.textContent=select.getAttribute('aria-label')||t('Выберите значение','Оберіть значення');var search=document.createElement('input');search.placeholder=t('Поиск…','Пошук…');search.setAttribute('aria-label',search.placeholder);var list=document.createElement('div');list.className='zg-custom-options';var cancel=document.createElement('button');cancel.type='button';cancel.textContent=t('Закрыть','Закрити');cancel.onclick=function(){close();select.focus();};panel.append(title,search,list,cancel);document.body.appendChild(panel);
 function render(){list.replaceChildren();Array.from(select.options).filter(function(o){return o.textContent.toLowerCase().includes(search.value.toLowerCase());}).forEach(function(o){var b=document.createElement('button');b.type='button';b.disabled=o.disabled;b.textContent=(o.selected?'✓ ':'◇ ')+o.textContent;b.setAttribute('aria-pressed',String(o.selected));b.onclick=function(){select.value=o.value;close();select.focus();select.dispatchEvent(new Event('change',{bubbles:true}));};list.appendChild(b);});}
 search.oninput=render;panel.addEventListener('click',function(e){if(e.target===panel)close();});panel.addEventListener('cancel',function(){close();});render();panel.showModal();search.focus();}
 function target(e){var s=e.target.closest('select');return s&&s.closest('#zg-story-editor,#zg-story-stage-settings,#zg-story-actors,#zg-story-episodes')?s:null;}
 w.ZargotaStoryMenus={createScene:function(done){var d=document.createElement('dialog');d.className='zg-custom-menu';var h=document.createElement('header');h.textContent=t('Новая локация','Нова локація');var input=document.createElement('input');input.placeholder=t('Название локации','Назва локації');input.setAttribute('aria-label',input.placeholder);var note=document.createElement('p');note.textContent=t('Текущая локация останется в эпизоде.','Поточна локація залишиться в епізоді.');var yes=document.createElement('button');yes.textContent=t('＋ Создать','＋ Створити');yes.onclick=function(){var name=input.value.trim();if(!name){input.focus();return;}d.remove();done(name);};var no=document.createElement('button');no.textContent=t('Отмена','Скасувати');no.onclick=function(){d.remove();};d.append(h,input,note,yes,no);document.body.appendChild(d);d.showModal();input.focus();}};
})(window);
