(function(w){
  'use strict';
  var activeTab='hero',speakerKey='',search='',catalog=null;
  var actorProject='default';
  function remember(){try{localStorage.setItem('zg-story-actor-view:'+actorProject,JSON.stringify({tab:activeTab,speaker:speakerKey}));}catch(e){}}
  function rename(record,value){var uk=w.ZargotaI18n&&w.ZargotaI18n.getLocale()==='uk',field=uk?'nameUk':'name',other=uk?'name':'nameUk',before=record[field];record[field]=value;if(!record[other]||record[other]===before||['Новый персонаж','Новий персонаж','Новая эмоция','Нова емоція'].includes(record[other]))record[other]=value;}
  if(w.addEventListener)w.addEventListener('beforeunload',function(){var input=document.activeElement;if(input&&input.matches('input')&&input.closest('#zg-story-actors'))input.dispatchEvent(new Event('change',{bubbles:true}));});
  function clone(v){return JSON.parse(JSON.stringify(v));}
  function t(ru,uk){return w.ZargotaI18n&&w.ZargotaI18n.getLocale()==='uk'?uk:ru;}
  function local(v,key){if(key==='name'&&['Новий персонаж','Нова емоція'].includes(v.nameUk)&&v.name&&!['Новый персонаж','Новая эмоция'].includes(v.name))return v.name;return w.ZargotaI18n&&w.ZargotaI18n.getLocale()==='uk'&&v[key+'Uk']||v[key]||'';}
  function el(tag,text){var e=document.createElement(tag);if(text!=null)e.textContent=text;return e;}
  function btn(text,fn){var b=el('button',text);b.type='button';b.onclick=fn;return b;}
  function field(host,text,value,fn,type){var label=el('label',text),input=el('input');input.type=type||'text';input.value=value==null?'':value;input.onchange=function(){fn(type==='number'?Number(input.value):input.value);};label.appendChild(input);host.appendChild(label);return input;}
  function select(host,text,value,options,fn){var label=el('label',text),input=el('select');options.forEach(function(p){var opt=el('option',p[1]);opt.value=p[0];input.appendChild(opt);});input.value=value||'';input.onchange=function(){fn(input.value);};label.appendChild(input);host.appendChild(label);return input;}
  function imageField(host,text,value,fn){var input=field(host,text,value,fn);if(w.ZargotaStoryAssets)w.ZargotaStoryAssets.attach(input,'image');if(value){var img=el('img');img.src=value;img.alt=text;img.className='zg-story-actor-preview';host.appendChild(img);}}
  function notice(text){if(w.showToast)w.showToast(text);}
  function character(data){var token=(data.scene&&data.scene.tokens||[]).find(function(x){return x.id===data.heroTokenId;})||{};return Object.assign({name:token.name||t('Герой','Герой'),portrait:token.image||'',hp:10,hpMax:10,ac:10,speed:7,initiative:0,level:1,stats:{str:0,dex:0,int:0,cha:0,per:0,con:0},inventoryItems:[]},clone(data.player||{}));}
  function portrait(data,node,runtimeCharacter){var base=node.speaker==='@player'?Object.assign({},(data.speakers||{})[data.playerSpeakerId]||{},character(data)):(data.speakers||{})[node.speaker]||{},emotion=(base.emotions||{})[node.emotion]||{},result=node.portrait?Object.assign({},base,{portrait:node.portrait,position:'50% 50%',zoom:1}):emotion.portrait?Object.assign({},base,emotion):Object.assign({},base);if(w.ZargotaStoryOutfits)result=w.ZargotaStoryOutfits.resolve(data,node,runtimeCharacter,result);return Object.assign(result,{name:base.name,nameUk:base.nameUk},node.portraitOverride===false?{}:node.portraitFrame||{});}
  function mutate(source,operation){var rules=w.ZargotaEquipmentRules;if(!rules||!rules.applyCreatureInventory)return{ok:false};return rules.applyCreatureInventory(source,operation);}
  function inventory(host,source,save,editing){
    var list=el('div');list.className='zg-story-inventory-list';host.appendChild(list);
    (source.inventoryItems||[]).forEach(function(item,index){var row=el('article'),details=el('details'),summary=el('summary');if(w.ZargotaStoryItems?.icon(item)||item.image){var art=el('img');art.src=w.ZargotaStoryItems?.icon(item)||item.image;art.alt='';summary.appendChild(art);}summary.appendChild(el('strong',item.name||item.itemId));summary.appendChild(el('small',' ×'+(item.qty||1)+(item.charges!=null?' · '+item.charges+'/'+(item.maxCharges==null?item.charges:item.maxCharges):'')));details.append(summary,el('p',item.description||item.effectText||item.effect||''));row.appendChild(details);
      function act(action){var result=mutate(source,{action:action,index:index,usedAt:Date.now()});if(result.ok)save(result.source);else notice(t('Действие недоступно: проверьте заряды и совместимость слотов.','Дія недоступна: перевірте заряди й сумісність слотів.'));}
      row.appendChild(btn(item.equipped?t('Снять','Зняти'):t('Экипировать','Спорядити'),function(){act('equip');}));
      if(item.charges!=null||item.consumption||/consum|расход|зель|эликсир|свиток/.test(item.category||''))row.appendChild(btn(t('Потратить','Витратити'),function(){act('use');}));
      if(editing)row.appendChild(btn(t('Удалить','Видалити'),function(){act('remove');}));list.appendChild(row);
    });
    if(!(source.inventoryItems||[]).length)list.appendChild(el('p',t('Рюкзак пуст','Наплічник порожній')));
    if(editing)host.appendChild(el('p',t('Экипировка использует общие правила предметов. «Потратить» списывает количество или заряд; эффекты из описания не применяются автоматически.','Спорядження використовує спільні правила предметів. «Витратити» списує кількість або заряд; ефекти з опису не застосовуються автоматично.')));
    if(!editing)return;
    var searchInput=field(host,t('Поиск в общем каталоге','Пошук у спільному каталозі'),search,function(v){search=v;save(source);});searchInput.type='search';
    if(!catalog&&w.ZargotaItemEconomy)catalog=w.ZargotaItemEconomy.getShopSeedItems();
    var items=(catalog||[]).filter(function(i){return !search||String(i.name||'').toLowerCase().includes(search.toLowerCase());}).slice(0,100),choice=select(host,t('Предмет из каталога · первые 100 совпадений','Предмет із каталогу · перші 100 збігів'),'',[['',t('Выберите предмет','Оберіть предмет')]].concat(items.map(function(i){return[i.id,i.name];})),function(){});
    host.appendChild(btn(t('Добавить из каталога','Додати з каталогу'),function(){var definition=items.find(function(i){return String(i.id)===choice.value;});if(!definition)return;var item=w.ZargotaItemEconomy.definitionToInventorySnapshot(definition,'story-item-'+Date.now(),1),result=mutate(source,{action:'add',item:item});if(result.ok)save(result.source);}));
    var custom=el('details');custom.appendChild(el('summary',t('＋ Собственный предмет','＋ Власний предмет')));host.appendChild(custom);
    var draft={name:'',description:'',category:'key',qty:1};field(custom,t('Название','Назва'),'',function(v){draft.name=v;});field(custom,t('Описание','Опис'),'',function(v){draft.description=v;});field(custom,t('Изображение · URL / путь','Зображення · URL / шлях'),'',function(v){draft.image=v;});field(custom,t('Количество','Кількість'),1,function(v){draft.qty=Math.max(1,v);},'number');select(custom,t('Тип','Тип'),'key',[['key',t('Сюжетный предмет','Сюжетний предмет')],['consumable',t('Расходник','Витратний предмет')],['other',t('Прочее','Інше')]],function(v){draft.category=v;});custom.appendChild(btn(t('Добавить предмет','Додати предмет'),function(){if(!draft.name.trim())return;var result=mutate(source,{action:'add',item:Object.assign({itemId:'story-item-'+Date.now()},draft)});if(result.ok)save(result.source);}));
  }
  function modal(){var root=document.getElementById('zg-story-actors');if(!root){root=el('section');root.id='zg-story-actors';root.setAttribute('role','dialog');root.setAttribute('aria-label',t('Герой, инвентарь и портреты','Герой, інвентар і портрети'));document.body.appendChild(root);}root.hidden=false;root.classList.remove('zg-story-play-bag');root.replaceChildren();return root;}
  function stats(host,c,save,editing){var grid=el('div');grid.className='zg-story-actor-stats';host.appendChild(grid);[['hp',t('HP сейчас','HP зараз')],['hpMax',t('HP максимум','HP максимум')],['ac',t('Защита','Захист')],['speed',t('Скорость','Швидкість')],['initiative',t('Инициатива','Ініціатива')],['level',t('Уровень','Рівень')]].forEach(function(p){if(editing||p[0]==='hp')field(grid,p[1],c[p[0]],function(v){var next=clone(c);next[p[0]]=Math.max(p[0]==='hpMax'||p[0]==='level'?1:p[0]==='initiative'?-100:0,v);next.hp=Math.min(next.hp,next.hpMax);save(next);},'number');else grid.appendChild(el('span',p[1]+': '+c[p[0]]));});
    var names={str:['Сила','Сила'],dex:['Ловкость','Спритність'],int:['Интеллект','Інтелект'],cha:['Харизма','Харизма'],per:['Восприятие','Сприйняття'],con:['Выносливость','Витривалість']};Object.keys(names).forEach(function(key){if(editing)field(grid,t.apply(null,names[key]),(c.stats||{})[key]||0,function(v){var next=clone(c);next.stats=next.stats||{};next.stats[key]=v;save(next);},'number');else grid.appendChild(el('span',t.apply(null,names[key])+': '+((c.stats||{})[key]||0)));});
  }
  function open(data,save,projectId){if(projectId!=null){actorProject=projectId;var view={};try{view=JSON.parse(localStorage.getItem('zg-story-actor-view:'+actorProject)||'{}');}catch(e){}activeTab=view.tab==='speakers'?'speakers':'hero';speakerKey=view.speaker||'';}var root=modal(),header=el('header');header.append(el('strong',t('Герой, инвентарь и эмоции','Герой, інвентар і емоції')),btn('×',close));root.appendChild(header);var nav=el('nav');[['hero',t('Герой и инвентарь','Герой та інвентар')],['speakers',t('Портреты и эмоции','Портрети й емоції')]].forEach(function(p){nav.appendChild(btn(p[1],function(){activeTab=p[0];remember();open(data,save);}));});nav.appendChild(btn(t('✦ AI-портреты · создать персонажа','✦ AI-портрети · створити персонажа'),function(){w.ZargotaStoryPortraitKit.open(save,function(id){speakerKey=id;activeTab='speakers';remember();});}));root.appendChild(nav);if(w.ZargotaStoryCastLibrary)w.ZargotaStoryCastLibrary.install(root,data,save,actorProject);var body=el('div');body.className='zg-story-actor-body';root.appendChild(body);
    if(activeTab==='hero'){
      var c=character(data);function saveCharacter(next){save(function(d){d.player=next;var token=(d.scene.tokens||[]).find(function(x){return x.id===d.heroTokenId;});if(token){token.name=next.name;token.nameUk=next.nameUk||next.name;if(next.tokenImage)token.image=next.tokenImage;}});}
      select(body,t('Игрок управляет токеном','Гравець керує токеном'),data.heroTokenId,[['',t('Выберите токен','Оберіть токен')]].concat((data.scene&&data.scene.tokens||[]).filter(function(x){return x.type!=='note';}).map(function(x){return[x.id,x.name||x.id];})),function(v){save(function(d){d.heroTokenId=v;});});
      body.appendChild(btn(t('＋ Создать токен героя','＋ Створити токен героя'),function(){save(function(d){d.scene=d.scene||{boardWidth:24,boardHeight:16,gridSize:64};d.scene.tokens=d.scene.tokens||[];var id='story-hero-'+Date.now();d.scene.tokens.push({id:id,type:'custom',name:c.name,image:c.tokenImage||c.portrait,x:50,y:50,size:68,visible:true});d.heroTokenId=id;d.player=c;});}));
      field(body,t('Имя героя','Ім’я героя'),c.name,function(v){saveCharacter(Object.assign({},c,{name:v}));});imageField(body,t('Портрет героя','Портрет героя'),c.portrait,function(v){saveCharacter(Object.assign({},c,{portrait:v}));});imageField(body,t('Изображение токена','Зображення токена'),c.tokenImage||'',function(v){saveCharacter(Object.assign({},c,{tokenImage:v}));});field(body,t('Описание · RU','Опис · RU'),c.description||'',function(v){saveCharacter(Object.assign({},c,{description:v}));});field(body,t('Описание · UK','Опис · UK'),c.descriptionUk||'',function(v){saveCharacter(Object.assign({},c,{descriptionUk:v}));});
      select(body,t('Герой говорит как','Герой говорить як'),data.playerSpeakerId,[['',t('Не привязывать к говорящему','Не прив’язувати до мовця')]].concat(Object.keys(data.speakers||{}).map(function(key){return[key,local(data.speakers[key],'name')||key];})),function(v){save(function(d){d.playerSpeakerId=v;});});
      var identity=el('section');identity.className='zg-actor-column zg-actor-identity';while(body.firstChild)identity.appendChild(body.firstChild);body.appendChild(identity);body.classList.add('zg-actor-columns');
      var attributes=el('section');attributes.className='zg-actor-column';attributes.appendChild(el('h3',t('Характеристики','Характеристики')));stats(attributes,c,saveCharacter,true);attributes.appendChild(el('p',t('Герой этого эпизода. Основной лист персонажа не изменяется.','Герой цього епізоду. Основний аркуш персонажа не змінюється.')));body.appendChild(attributes);
      var items=el('section');items.className='zg-actor-column zg-actor-items';items.appendChild(el('h3',t('Начальный инвентарь','Початковий інвентар')));if(w.ZargotaStoryItems)w.ZargotaStoryItems.edit(data,items,save);inventory(items,c,saveCharacter,true);body.appendChild(items);
    }else{
      var speakers=data.speakers||{},keys=Object.keys(speakers).filter(function(id){return !speakers[id].archived;});if(!speakers[speakerKey]||speakers[speakerKey].archived)speakerKey=keys[0]||'';
      select(body,t('Говорящий','Мовець'),speakerKey,keys.map(function(key){return[key,local(speakers[key],'name')||key];}),function(v){speakerKey=v;remember();open(data,save);});body.appendChild(btn(t('＋ Добавить говорящего','＋ Додати мовця'),function(){speakerKey='speaker-'+Date.now();remember();save(function(d){d.speakers=d.speakers||{};d.speakers[speakerKey]={name:'Новый персонаж',nameUk:'Новий персонаж',portrait:'',emotions:{}};});}));directory(data,body,save);if(!speakerKey)return;var key=speakerKey,speaker=speakers[key];function setSpeaker(field,value){save(function(d){d.speakers[key][field]=value;});}
      field(body,t('Имя говорящего','Ім’я мовця'),local(speaker,'name'),function(v){save(function(d){rename(d.speakers[key],v);});});imageField(body,t('Обычный портрет','Звичайний портрет'),speaker.portrait||'',function(v){save(function(d){Object.assign(d.speakers[key],{portrait:v,position:'50% 50%',zoom:1});});});if(w.ZargotaStoryOutfits)w.ZargotaStoryOutfits.edit(data,key,body,save);
      body.appendChild(el('p',t('Эмоция выбирается отдельно у каждой реплики. Без выбора используется обычный портрет. Загружайте голову и плечи — смена изображения не требует анимации.','Емоція обирається окремо для кожної репліки. Без вибору використовується звичайний портрет. Завантажуйте голову й плечі — зміна зображення не потребує анімації.')));
      var profile=el('section');profile.className='zg-actor-column';while(body.firstChild)profile.appendChild(body.firstChild);body.appendChild(profile);body.classList.add('zg-actor-portraits');var emotions=el('section');emotions.className='zg-actor-column zg-actor-emotions';emotions.appendChild(el('h3',t('Эмоции','Емоції')));body.appendChild(emotions);
      Object.keys(speaker.emotions||{}).forEach(function(id){var emotion=speaker.emotions[id],box=el('fieldset');box.appendChild(el('legend',local(emotion,'name')||id));field(box,t('Название эмоции','Назва емоції'),local(emotion,'name'),function(v){save(function(d){rename(d.speakers[key].emotions[id],v);});});imageField(box,t('Портрет эмоции','Портрет емоції'),emotion.portrait||'',function(v){save(function(d){Object.assign(d.speakers[key].emotions[id],{portrait:v,position:'50% 50%',zoom:1});});});box.appendChild(btn(t('Удалить эмоцию','Видалити емоцію'),function(){save(function(d){delete d.speakers[key].emotions[id];});}));emotions.appendChild(box);});emotions.appendChild(btn(t('＋ Добавить эмоцию','＋ Додати емоцію'),function(){save(function(d){d.speakers[key].emotions=d.speakers[key].emotions||{};d.speakers[key].emotions['emotion-'+Date.now()]={name:'Новая эмоция',nameUk:'Нова емоція',portrait:speaker.portrait,position:speaker.position,zoom:speaker.zoom};});}));
    }
  }
  function enhance(data,node,host,save){var box=el('fieldset');box.className='zg-story-extra';box.appendChild(el('legend',t('Портрет этой реплики','Портрет цієї репліки')));if(w.ZargotaStoryPortraitKit){box.classList.add('zg-first-portrait');w.ZargotaStoryPortraitKit.picker(data,node,box,function(patch){save(function(d){Object.assign(d.nodes.find(function(n){return n.id===node.id;}),patch);});},true);host.appendChild(box);return;}var speaker=(data.speakers||{})[node.speaker==='@player'?data.playerSpeakerId:node.speaker]||{};select(box,t('Эмоция','Емоція'),node.emotion,[['',t('Обычный портрет','Звичайний портрет')]].concat(Object.keys(speaker.emotions||{}).map(function(key){return[key,local(speaker.emotions[key],'name')||key];})),function(v){save(function(d){d.nodes.find(function(n){return n.id===node.id;}).emotion=v;});});field(box,t('Другой портрет только здесь · URL / путь','Інший портрет лише тут · URL / шлях'),node.portrait||'',function(v){save(function(d){d.nodes.find(function(n){return n.id===node.id;}).portrait=v;});});var resolved=portrait(data,node);if(resolved.portrait){var preview=el('img');preview.src=resolved.portrait;preview.alt=t('Портрет выбранной реплики','Портрет обраної репліки');preview.className='zg-story-actor-preview';box.appendChild(preview);}host.appendChild(box);}
  function inspectItem(item,trigger){
    var dialog=el('dialog');dialog.className='zg-story-item-inspection';
    var art=el('img');art.src=item.inspectImage;art.alt=local(item,'name')||'';
    var back=btn(t('Закрыть осмотр','Закрити огляд'),function(){dialog.close();});
    dialog.append(art,back);document.body.appendChild(dialog);
    dialog.addEventListener('close',function(){dialog.remove();if(trigger&&trigger.isConnected)trigger.focus();},{once:true});
    dialog.addEventListener('keydown',function(e){e.stopPropagation();});
    dialog.showModal();back.focus();
  }
  function showCharacter(c,save,onClose){
    var root=modal(),header=el('header');document.body.appendChild(root);root.classList.remove('zg-story-embedded');root.classList.add('zg-story-play-bag');root.setAttribute('aria-label',t('Инвентарь','Інвентар'));
    function dismissBag(){close();if(onClose)onClose();}
    var icon=el('img');icon.src='images/vtt-icons/inventory.png';icon.alt='';var dismiss=btn('×',dismissBag);dismiss.setAttribute('aria-label',t('Закрыть сумку','Закрити сумку'));header.append(icon,dismiss);root.appendChild(header);
    var grid=el('div');grid.className='zg-story-bag-grid';root.appendChild(grid);var detail=el('div');detail.className='zg-story-bag-detail';detail.hidden=true;root.appendChild(detail);
    var items=c.inventoryItems||[];for(var i=0;i<Math.max(9,Math.ceil(items.length/3)*3);i++)(function(index){var item=items[index],slot=btn('',function(){
      if(item.storyUnread){delete item.storyUnread;slot.classList.remove('is-new-item');var newMark=slot.querySelector('.zg-story-item-new');if(newMark)newMark.remove();slot.setAttribute('aria-label',(local(item,'name')||item.itemId)+' ×'+(item.qty||1));save(c);}
      detail.replaceChildren(el('strong',local(item,'name')||item.itemId),el('p',local(item,'description')||item.effectText||item.effect||''));detail.hidden=false;
      function act(action){var result=mutate(c,{action:action,index:index,usedAt:Date.now()});if(result.ok){var sound=action==='use'?item.useSound:action==='equip'&&!item.equipped?item.equipSound:'';if(sound){var audio=new Audio(sound);audio.volume=.6;audio.play().catch(function(){});}save(result.source);showCharacter(result.source,save,onClose);}else notice(t('Действие недоступно: проверьте заряды и совместимость слотов.','Дія недоступна: перевірте заряди й сумісність слотів.'));}
      if(item.inspectImage)detail.appendChild(btn(t('Осмотреть','Оглянути'),function(){inspectItem(item,this);}));
      if(item.category!=='key')detail.appendChild(btn(item.equipped?t('Снять','Зняти'):t('Экипировать','Спорядити'),function(){act('equip');}));if(item.useSound||item.charges!=null||item.consumption||/consum|расход|зель|эликсир|свиток/.test(item.category||''))detail.appendChild(btn(t('Использовать','Використати'),function(){act('use');}));
    });slot.className='zg-story-bag-slot';if(!item){slot.disabled=true;slot.setAttribute('aria-label',t('Пустой слот','Порожня комірка'));}else{slot.title=local(item,'name')||item.itemId;slot.setAttribute('aria-label',slot.title+' ×'+(item.qty||1));if(w.ZargotaStoryItems?.icon(item)||item.image){var art=el('img');art.src=w.ZargotaStoryItems?.icon(item)||item.image;art.alt='';slot.appendChild(art);}else slot.appendChild(el('span',slot.title));if(item.storyUnread){slot.classList.add('is-new-item');var mark=el('span',t('Новое','Нове'));mark.className='zg-story-item-new';slot.appendChild(mark);slot.setAttribute('aria-label',slot.getAttribute('aria-label')+' · '+t('Новый предмет','Новий предмет'));}if(item.qty>1)slot.appendChild(el('small',item.qty));if(item.equipped){var equipped=el('b','◆');equipped.title=t('Экипировано','Споряджено');slot.appendChild(equipped);}}grid.appendChild(slot);})(i);
    root.onkeydown=function(e){if(e.key==='Escape'){e.stopPropagation();dismissBag();}};
  }
  function close(){var root=document.getElementById('zg-story-actors');if(root)root.hidden=true;}
  function directory(data,body,save){
    var speakers=data.speakers||{},list=el('nav');list.className='zg-speaker-list zg-speaker-list-compact';list.setAttribute('aria-label',t('Список персонажей','Список персонажів'));
    var query=el('input');query.type='search';query.placeholder=t('Найти персонажа…','Знайти персонажа…');query.setAttribute('aria-label',query.placeholder);query.className='zg-speaker-search';
    Object.keys(speakers).filter(function(id){return !speakers[id].archived;}).sort(function(a,b){return Number(!!speakers[a].originEpisode)-Number(!!speakers[b].originEpisode)||local(speakers[a],'name').localeCompare(local(speakers[b],'name'));}).forEach(function(id){var b=btn('',function(){speakerKey=id;remember();open(data,save);});b.dataset.search=local(speakers[id],'name').toLowerCase();b.setAttribute('aria-pressed',String(id===speakerKey));var img=el(speakers[id].portrait?'img':'span');if(speakers[id].portrait){img.src=speakers[id].portrait;img.alt='';}else img.textContent='♙';b.append(img,el('span',local(speakers[id],'name')||id));b.title=id;list.appendChild(b);});
    query.oninput=function(){var term=query.value.trim().toLowerCase();Array.from(list.children).forEach(function(b){b.hidden=!b.dataset.search.includes(term);});};
    var tools=el('section');tools.className='zg-speaker-directory';tools.append(query,list);
    if(speakerKey){var armed=false,remove=btn(t('⌫ Удалить персонажа','⌫ Видалити персонажа'),function(){if(!armed){armed=true;remove.textContent=t('Подтвердить · убрать в архив','Підтвердити · прибрати до архіву');return;}var key=speakerKey;speakerKey=Object.keys(speakers).find(function(id){return id!==key&&!speakers[id].archived;})||'';remember();save(function(d){d.speakers[key].archived=true;});});tools.appendChild(remove);}
    var archived=Object.keys(speakers).filter(function(id){return speakers[id].archived;});if(archived.length){var fold=el('details');fold.appendChild(el('summary',t('Архив персонажей','Архів персонажів')+' · '+archived.length));fold.appendChild(el('p',t('Удалённые персонажи остаются в старых репликах. Их можно восстановить вместе с эмоциями.','Видалені персонажі залишаються у старих репліках. Їх можна відновити разом з емоціями.')));archived.forEach(function(id){fold.appendChild(btn(t('↶ Восстановить: ','↶ Відновити: ')+local(speakers[id],'name'),function(){speakerKey=id;remember();save(function(d){delete d.speakers[id].archived;});}));});tools.appendChild(fold);}
    body.prepend(tools);
  }
  w.ZargotaStoryActors={displayName:function(actor){return local(actor||{},'name');},open:open,enhance:enhance,character:character,portrait:portrait,mutate:mutate,showCharacter:showCharacter,close:close};
})(window);
