(function(w){
  'use strict';
  var hooks=null,root=null,wire=null,menu=null;
  function t(ru,uk){return w.ZargotaI18n&&w.ZargotaI18n.getLocale()==='uk'?uk:ru;}
  function local(o,k){return w.ZargotaI18n&&w.ZargotaI18n.getLocale()==='uk'?o[k+'Uk']||o[k]||'':o[k]||'';}
  function el(tag,cls,text){var e=document.createElement(tag);if(cls)e.className=cls;if(text!=null)e.textContent=text;return e;}
  function uid(){return 'graph-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);}
  function node(data,id){return(data.nodes||[]).find(function(n){return n.id===id;});}
  function outputs(n){return n.links&&n.links.length?n.links:[{id:'',to:'',label:''}];}
  function connect(data,from,edgeId,to){var a=node(data,from),b=node(data,to);if(!a||!b||a===b)return false;a.links=a.links||[];var link=a.links.find(function(l){return l.id===edgeId;});if(edgeId&&!link)return false;if(!link){link={id:uid(),label:'',labelUk:'',delayMs:0};a.links.push(link);}link.to=to;delete link.sceneId;return true;}
  function closeMenu(){if(menu){menu.remove();menu=null;}}
  function clearWire(){wire=null;var line=document.getElementById('zg-story-wire-draft');if(line)line.remove();if(root)root.classList.remove('zg-wiring');}
  function position(e){var box=root.querySelector('#zg-story-stage').getBoundingClientRect(),z=w.ZargotaStoryGraph.scale||1;return{x:Math.min(7800,Math.max(12,(e.clientX-box.left)/z)),y:Math.min(7800,Math.max(12,(e.clientY-box.top)/z))};}
  function create(kind,p){var id=uid();hooks.update(function(data){var title=kind==='choice'?['Выбор','Вибір']:kind==='image'?['Картинка','Зображення']:['Диалог','Діалог'];data.nodes.push({id:id,kind:kind,title:title[0],titleUk:title[1],speaker:'',text:'',textUk:'',x:p.x,y:p.y,links:kind==='choice'?[1,2].map(function(i){return{id:uid(),to:'',label:'Вариант '+i,labelUk:'Варіант '+i,delayMs:0};}):[]});hooks.select(id);});}
  function openMenu(e){e.preventDefault();closeMenu();clearWire();var p=position(e);menu=el('div','zg-graph-menu');menu.setAttribute('role','menu');menu.setAttribute('aria-label',t('Добавить на доску','Додати на дошку'));menu.style.left=Math.max(8,Math.min(innerWidth-220,e.clientX))+'px';menu.style.top=Math.max(8,Math.min(innerHeight-170,e.clientY))+'px';[['dialogue','◇',t('Диалог','Діалог')],['image','▧',t('Картинка','Зображення')],['choice','⑂',t('Выбор','Вибір')]].forEach(function(preset){var b=el('button','',preset[1]+' '+preset[2]);b.type='button';b.setAttribute('role','menuitem');b.onclick=function(){closeMenu();create(preset[0],p);};menu.appendChild(b);});root.appendChild(menu);menu.querySelector('button').focus();}
  function svgEl(tag,attrs){var e=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.keys(attrs).forEach(function(k){e.setAttribute(k,attrs[k]);});return e;}
  function path(x,y,xx,yy){var bend=Math.max(65,Math.abs(xx-x)*.45);return'M '+x+' '+y+' C '+(x+bend)+' '+y+' '+(xx-bend)+' '+yy+' '+xx+' '+yy;}
  function edges(data){if(!root)return;var stage=root.querySelector('#zg-story-stage'),svg=root.querySelector('#zg-story-links');var width=Math.max(1200,...data.nodes.map(function(n){return Number(n.x||0)+330;})),height=Math.max(760,...data.nodes.map(function(n){return Number(n.y||0)+160+outputs(n).length*32;}));stage.style.width=width+'px';stage.style.height=height+'px';svg.setAttribute('viewBox','0 0 '+width+' '+height);svg.replaceChildren();var defs=svgEl('defs',{}),marker=svgEl('marker',{id:'zg-story-arrow',viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:7,markerHeight:7,orient:'auto'});marker.appendChild(svgEl('path',{d:'M 0 0 L 10 5 L 0 10 z',fill:'#8fbbab'}));defs.appendChild(marker);svg.appendChild(defs);
    data.nodes.forEach(function(n){(n.links||[]).forEach(function(link,i){var target=node(data,link.to);if(!target)return;var x=Number(n.x||0)+220,y=Number(n.y||0)+112+i*32,xx=Number(target.x||0),yy=Number(target.y||0)+42;var line=svgEl('path',{class:'zg-story-link','data-story-link':link.id,'data-from':n.id,d:path(x,y,xx,yy)});svg.appendChild(line);var title=svgEl('title',{});title.textContent=(i+1)+'. '+(local(link,'label')||t('Продолжить','Продовжити'));line.appendChild(title);});});
  }
  function decorate(data,selected){if(!root)return;root.querySelectorAll('.zg-story-node').forEach(function(card){var n=node(data,card.dataset.nodeId);if(!n)return;card.querySelectorAll('.zg-graph-ports,.zg-graph-in,.zg-graph-kind').forEach(function(e){e.remove();});card.dataset.kind=n.kind||'dialogue';var badge=el('div','zg-graph-kind',n.kind==='choice'?t('⑂ Выбор','⑂ Вибір'):n.kind==='image'?t('▧ Картинка','▧ Зображення'):t('◇ Диалог','◇ Діалог'));card.prepend(badge);var input=el('button','zg-graph-in','');input.type='button';input.dataset.graphInput=n.id;input.setAttribute('aria-label',t('Вход: ','Вхід: ')+local(n,'title'));card.appendChild(input);var ports=el('div','zg-graph-ports');outputs(n).forEach(function(link,i){var row=el('div','zg-graph-port-row');row.appendChild(el('span','',local(link,'label')||t('Продолжить','Продовжити')));var b=el('button','zg-graph-out',String(i+1));b.type='button';b.dataset.graphFrom=n.id;b.dataset.graphEdge=link.id;b.dataset.graphIndex=i;b.setAttribute('aria-label',t('Выход ','Вихід ')+(i+1)+': '+local(n,'title'));row.appendChild(b);ports.appendChild(row);});card.appendChild(ports);});
    root.querySelectorAll('.zg-story-node').forEach(function(card){var n=node(data,card.dataset.nodeId);if(n)card.style.height=(108+outputs(n).length*32)+'px';});
    var host=root.querySelector('#zg-story-inspector'),n=node(data,selected);if(!n||host.querySelector('.zg-graph-advanced'))return;
    var advanced=el('details','zg-graph-advanced'),summary=el('summary','',t('Дополнительно · связи и переходы','Додатково · зв’язки та переходи'));advanced.appendChild(summary);
    host.querySelectorAll('.zg-story-link-row,[data-story-add-link]').forEach(function(e){advanced.appendChild(e);});
    Array.from(host.children).forEach(function(e){if(e.tagName==='BUTTON'&&/Создать следующую|Створити наступну/.test(e.textContent))advanced.appendChild(e);if(e.tagName==='H3'&&/^(Связи|Зв’язки)$/.test(e.textContent))e.remove();});host.appendChild(advanced);
    if(n.kind==='choice'){var choices=el('section','zg-graph-choice-editor');choices.appendChild(el('h3','',t('Варианты ответа','Варіанти відповіді')));(n.links||[]).forEach(function(link,i){var label=el('label','zg-story-field',t('Выбор ','Вибір ')+(i+1)),input=el('input');input.value=local(link,'label');input.onchange=function(){hooks.update(function(d){var l=node(d,n.id).links.find(function(l){return l.id===link.id;});l[w.ZargotaI18n&&w.ZargotaI18n.getLocale()==='uk'?'labelUk':'label']=input.value;});};label.appendChild(input);var remove=el('button','',t('Удалить вариант','Видалити варіант'));remove.type='button';remove.onclick=function(){hooks.update(function(d){node(d,n.id).links=node(d,n.id).links.filter(function(l){return l.id!==link.id;});});};label.appendChild(remove);choices.appendChild(label);});var add=el('button','',t('＋ Добавить вариант','＋ Додати варіант'));add.type='button';add.onclick=function(){hooks.update(function(d){var n1=node(d,n.id);n1.links.push({id:uid(),to:'',label:'Новый вариант',labelUk:'Новий варіант',delayMs:0});});};choices.appendChild(add);host.prepend(choices);}
    if(n.kind==='image'){var media=host.querySelector('[data-story-extra="image"]');if(media)host.prepend(media.closest('fieldset'));}
  }
  function install(container,api){root=container;hooks=api;var canvas=root.querySelector('.zg-story-canvas');canvas.addEventListener('contextmenu',openMenu);root.addEventListener('pointerdown',function(e){if(menu&&!menu.contains(e.target))closeMenu();var port=e.target.closest('[data-graph-from]');if(!port||e.button!==0)return;e.preventDefault();e.stopImmediatePropagation();var n=node(hooks.get(),port.dataset.graphFrom);wire={from:n.id,edge:port.dataset.graphEdge,x:Number(n.x||0)+220,y:Number(n.y||0)+112+Number(port.dataset.graphIndex)*32,pointer:e.pointerId};root.classList.add('zg-wiring');},true);
    document.addEventListener('pointermove',function(e){if(!wire||wire.pointer!==e.pointerId)return;var p=position(e),svg=root.querySelector('#zg-story-links'),line=document.getElementById('zg-story-wire-draft');if(!line){line=svgEl('path',{id:'zg-story-wire-draft',class:'zg-story-link zg-wire-preview'});svg.appendChild(line);}line.setAttribute('d',path(wire.x,wire.y,p.x,p.y));});
    document.addEventListener('pointerup',function(e){if(!wire)return;var end=document.elementFromPoint(e.clientX,e.clientY),card=end&&end.closest('.zg-story-node'),saved=wire;clearWire();if(card)hooks.update(function(d){connect(d,saved.from,saved.edge,card.dataset.nodeId);});});
    root.addEventListener('click',function(e){var port=e.target.closest('[data-graph-from],[data-graph-input]');if(port){e.preventDefault();e.stopImmediatePropagation();}},true);
    document.addEventListener('keydown',function(e){if(e.key==='Escape'){closeMenu();clearWire();}});document.addEventListener('pointercancel',clearWire);
  }
  var basicInstall=install,basicEdges=edges,basicDecorate=decorate,inspectorTab='text';
  edges=function(data){basicEdges(data);var stage=root.querySelector('#zg-story-stage'),svg=root.querySelector('#zg-story-links');stage.style.width='8200px';stage.style.height='8200px';svg.setAttribute('viewBox','0 0 8200 8200');};
  decorate=function(data,selected){basicDecorate(data,selected);var host=root.querySelector('#zg-story-inspector');if(host.querySelector('.zg-inspector-tabs'))return;var tabs=el('nav','zg-inspector-tabs'),sections={};[['text',t('Реплика','Репліка')],['visual',t('Внешний вид','Вигляд')],['events',t('События','Події')],['links',t('Связи','Зв’язки')]].forEach(function(pair){var s=el('section','zg-inspector-section');s.dataset.tab=pair[0];sections[pair[0]]=s;var b=el('button','',pair[1]);b.type='button';b.onclick=function(){inspectorTab=pair[0];show();};tabs.appendChild(b);});Array.from(host.children).forEach(function(e){if(e.matches('h3,.zg-story-note')){e.remove();return;}var group=e.matches('.zg-graph-advanced')||e.querySelector('[data-story-field="entry"],input[readonly]')||e.matches('[data-story-remove-node]')?'links':e.matches('.zg-portrait-adjust')||e.querySelector('[data-story-extra="image"]')?'visual':e.matches('.zg-story-project-fields')||e.tagName==='FIELDSET'||e.querySelector('select:not([data-story-field])')?'events':'text';if(e.querySelector('[data-story-extra="image"]')){var fold=el('details');fold.open=node(data,selected).kind==='image';fold.appendChild(el('summary','',t('Картинка на весь экран','Зображення на весь екран')));fold.appendChild(e);sections[group].appendChild(fold);}else sections[group].appendChild(e);});host.appendChild(tabs);Object.values(sections).forEach(function(s){host.appendChild(s);});function show(){host.scrollTop=0;Object.keys(sections).forEach(function(k,i){sections[k].hidden=k!==inspectorTab;tabs.children[i].setAttribute('aria-pressed',String(k===inspectorTab));});}show();};
  install=function(container,api){basicInstall(container,api);var canvas=root.querySelector('.zg-story-canvas'),stage=root.querySelector('#zg-story-stage'),bar=el('nav','zg-board-tools'),slider=el('input'),label=el('span','','100%');slider.type='range';slider.min=.35;slider.max=1.5;slider.step=.05;slider.value=1;slider.setAttribute('aria-label',t('Масштаб доски','Масштаб дошки'));function zoom(value){var old=w.ZargotaStoryGraph.scale||1,next=Math.max(.35,Math.min(1.5,value)),x=(canvas.scrollLeft+canvas.clientWidth/2)/old,y=(canvas.scrollTop+canvas.clientHeight/2)/old;w.ZargotaStoryGraph.scale=next;stage.style.zoom=next;slider.value=next;label.textContent=Math.round(next*100)+'%';canvas.scrollLeft=x*next-canvas.clientWidth/2;canvas.scrollTop=y*next-canvas.clientHeight/2;}slider.oninput=function(){zoom(Number(this.value));};bar.append(slider,label,el('span','',t('Пробел + мышь · перемещение','Пробіл + миша · переміщення')));canvas.before(bar);var space=false,pan=null;document.addEventListener('keydown',function(e){if(e.code==='Space'&&!e.target.closest('input,textarea,select,button')&&root.classList.contains('open')){space=true;e.preventDefault();}});document.addEventListener('keyup',function(e){if(e.code==='Space')space=false;});w.addEventListener('blur',function(){space=false;pan=null;});canvas.addEventListener('pointerdown',function(e){if(e.button===1||(space&&e.button===0)){e.preventDefault();e.stopImmediatePropagation();pan={x:e.clientX,y:e.clientY,left:canvas.scrollLeft,top:canvas.scrollTop};}},true);document.addEventListener('pointermove',function(e){if(pan){canvas.scrollLeft=pan.left-e.clientX+pan.x;canvas.scrollTop=pan.top-e.clientY+pan.y;}});document.addEventListener('pointerup',function(){pan=null;});canvas.addEventListener('wheel',function(e){if(e.ctrlKey||e.metaKey){e.preventDefault();zoom((w.ZargotaStoryGraph.scale||1)-Math.sign(e.deltaY)*.05);}},{passive:false});};
  w.ZargotaStoryGraph={install:install,decorate:decorate,edges:edges,connect:connect,scale:1};
})(window);
