(function(w){
 'use strict';
 function t(ru,uk){return w.ZargotaI18n&&w.ZargotaI18n.getLocale()==='uk'?uk:ru;}
 var menu=null;
 function close(){if(menu){menu.remove();menu=null;}}
 function open(select){close();var panel=document.createElement('dialog');panel.className='zg-custom-menu';menu=panel;var title=document.createElement('header');title.textContent=select.getAttribute('aria-label')||t('Выберите значение','Оберіть значення');var search=document.createElement('input');search.placeholder=t('Поиск…','Пошук…');search.setAttribute('aria-label',search.placeholder);var list=document.createElement('div');list.className='zg-custom-options';var cancel=document.createElement('button');cancel.type='button';cancel.textContent=t('Закрыть','Закрити');cancel.onclick=function(){close();select.focus({preventScroll:true});};var locationFilter=null,locationRows=Array.isArray(select.storyMenuLocations)?select.storyMenuLocations:[];if(locationRows.length){var locationLabel=document.createElement('label');locationLabel.className='zg-custom-filter';var locationTitle=document.createElement('span');locationTitle.textContent=t('Локация','Локація');locationFilter=document.createElement('select');locationFilter.setAttribute('aria-label',t('Фильтр по локации','Фільтр за локацією'));var all=document.createElement('option');all.value='';all.textContent=t('Все локации','Усі локації');locationFilter.appendChild(all);locationRows.forEach(function(row){var option=document.createElement('option');option.value=row[0];option.textContent=row[1]||row[0];locationFilter.appendChild(option);});locationLabel.append(locationTitle,locationFilter);panel.append(title,locationLabel,search,list,cancel);}else panel.append(title,search,list,cancel);document.body.appendChild(panel);
 function render(){var location=locationFilter&&locationFilter.value;list.replaceChildren();Array.from(select.options).filter(function(o){var locations=[];try{locations=JSON.parse(o.dataset.storyLocations||'[]');}catch(e){}return(!location||!locations.length||locations.includes(location))&&o.textContent.toLowerCase().includes(search.value.toLowerCase());}).forEach(function(o){var b=document.createElement('button');b.type='button';b.disabled=o.disabled;b.textContent=(o.selected?'✓ ':'◇ ')+o.textContent;b.setAttribute('aria-pressed',String(o.selected));b.onclick=function(){select.value=o.value;close();select.focus({preventScroll:true});select.dispatchEvent(new Event('change',{bubbles:true}));};if(typeof select.storyDeleteOption==='function'){var row=document.createElement('div');row.style.cssText='display:flex;gap:8px;align-items:center';b.style.flex='1';var remove=document.createElement('button');remove.type='button';remove.textContent='⌫';remove.title=t('Удалить: ','Видалити: ')+o.textContent;remove.setAttribute('aria-label',remove.title);var armed=false;remove.onclick=function(){if(!armed){armed=true;remove.textContent=t('Удалить?','Видалити?');remove.setAttribute('aria-label',t('Подтвердить удаление: ','Підтвердити видалення: ')+o.textContent);return;}if(select.storyDeleteOption(o.value))render();};row.append(b,remove);list.appendChild(row);}else list.appendChild(b);});}
 search.oninput=render;if(locationFilter)locationFilter.onchange=render;panel.addEventListener('click',function(e){if(e.target===panel)close();});panel.addEventListener('cancel',function(){close();});render();panel.showModal();search.focus();}
 function target(e){var s=e.target.closest('select');return s&&s.closest('#zg-story-editor,#zg-story-stage-settings,#zg-story-actors,#zg-story-episodes')?s:null;}
 document.addEventListener('mousedown',function(e){var s=target(e);if(s&&e.button===0&&!s.disabled){e.preventDefault();open(s);}},true);document.addEventListener('keydown',function(e){var s=target(e);if(s&&!s.disabled&&[' ','Enter','ArrowDown'].includes(e.key)){e.preventDefault();e.stopPropagation();open(s);}},true);w.ZargotaStoryMenus={createScene:function(done){var d=document.createElement('dialog');d.className='zg-custom-menu';var h=document.createElement('header');h.textContent=t('Новая локация','Нова локація');var input=document.createElement('input');input.placeholder=t('Название локации','Назва локації');input.setAttribute('aria-label',input.placeholder);var note=document.createElement('p');note.textContent=t('Текущая локация останется в эпизоде.','Поточна локація залишиться в епізоді.');var yes=document.createElement('button');yes.textContent=t('＋ Создать','＋ Створити');yes.onclick=function(){var name=input.value.trim();if(!name){input.focus();return;}d.remove();done(name);};var no=document.createElement('button');no.textContent=t('Отмена','Скасувати');no.onclick=function(){d.remove();};d.append(h,input,note,yes,no);document.body.appendChild(d);d.showModal();input.focus();}};
})(window);
