(function(w){
 'use strict';
 var fields=['image','imageMotion','sound','typingSound','textSpeed','textAnimation','pageDelayMs','textSize','textWidth'];
 function t(a,b){return w.ZargotaI18n&&w.ZargotaI18n.getLocale()==='uk'?b:a;}
 var activeIndex=null;
 function index(data){var byId=new Map(),incoming=new Map();(data.nodes||[]).forEach(function(n){byId.set(n.id,n);(n.links||[]).forEach(function(l){if(!incoming.has(l.to))incoming.set(l.to,[]);incoming.get(l.to).push(n);});});return {data:data,byId:byId,incoming:incoming,sources:new Map()};}
 function batch(data,fn){var previous=activeIndex;activeIndex=index(data);try{return fn();}finally{activeIndex=previous;}}
 function source(data,node){if(!node||node.branchOverride||node.branchShared)return null;var idx=activeIndex&&activeIndex.data===data?activeIndex:index(data);if(node.branchSourceId)return idx.byId.get(node.branchSourceId)||null;if(idx.sources.has(node.id))return idx.sources.get(node.id);
   var queue=[node.id],seen=new Set(queue),found=new Map();for(var cursor=0;cursor<queue.length;cursor++){(idx.incoming.get(queue[cursor])||[]).forEach(function(n){if(seen.has(n.id))return;seen.add(n.id);if(n.branchShared)found.set(n.id,n);else queue.push(n.id);});}var result=found.size===1?Array.from(found.values())[0]:null;idx.sources.set(node.id,result);return result;
 }
 function resolve(data,node,seen){if(!node)return node;seen=seen||new Set();if(seen.has(node.id))return Object.assign({},node);seen.add(node.id);var parent=source(data,node),result=Object.assign({},node);if(parent&&!seen.has(parent.id)){var inherited=resolve(data,parent,seen);if(node.imageFit==null&&inherited.imageFit!=null)result.imageFit=inherited.imageFit;if(node.imageZoom==null&&inherited.imageZoom!=null)result.imageZoom=inherited.imageZoom;fields.forEach(function(k){if(inherited[k]===undefined)delete result[k];else result[k]=inherited[k];});}return result;}
 function share(data,id){var root=(data.nodes||[]).find(function(n){return n.id===id;});if(root){root.branchShared=true;root.branchOverride=false;delete root.branchSourceId;}}
 function enhance(data,node,host,save){var box=document.createElement('fieldset');box.className='zg-branch-settings';var legend=document.createElement('legend');legend.textContent=t('⌘ Общие настройки ветки','⌘ Спільні налаштування гілки');box.appendChild(legend);var parent=source(data,node),note=document.createElement('p');note.textContent=parent?t('Источник: ','Джерело: ')+(parent.titleUk&&w.ZargotaI18n&&w.ZargotaI18n.getLocale()==='uk'?parent.titleUk:parent.title||parent.id):t('Общий фон, движение камеры, звук печати и параметры текста. События и урон не копируются.','Спільне тло, рух камери, звук друку та параметри тексту. Події й шкода не копіюються.');box.appendChild(note);if(parent){var help=document.createElement('p');help.textContent=t('Эти параметры берутся из источника, а не из полей ниже. Меняйте исходный блок или включите собственные настройки. Старые значения блока сохранены.','Ці параметри беруться з джерела, а не з полів нижче. Змінюйте початковий блок або увімкніть власні налаштування. Старі значення блоку збережені.');box.appendChild(help);}
   var label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=!!node.branchOverride;label.append(input,document.createTextNode(t('Собственные настройки этого блока','Власні налаштування цього блоку')));input.onchange=function(){save(function(d){d.nodes.find(function(n){return n.id===node.id;}).branchOverride=input.checked;});};box.appendChild(label);
   var select=document.createElement('select');select.setAttribute('aria-label',t('Источник настроек ветки','Джерело налаштувань гілки'));var empty=document.createElement('option');empty.value='';empty.textContent=t('Автоматически · по связям','Автоматично · за зв’язками');select.appendChild(empty);(data.nodes||[]).filter(function(n){return n.id!==node.id;}).forEach(function(n){var o=document.createElement('option');o.value=n.id;o.textContent=(n.title||n.id);select.appendChild(o);});select.value=node.branchSourceId||'';select.onchange=function(){save(function(d){var n=d.nodes.find(function(n){return n.id===node.id;});n.branchSourceId=select.value;n.branchShared=false;n.branchOverride=false;});};box.appendChild(select);
   var button=document.createElement('button');button.type='button';button.textContent=node.branchShared?t('Отключить общие настройки ветки','Вимкнути спільні налаштування гілки'):t('Применять настройки к следующей ветке','Застосовувати налаштування до наступної гілки');button.onclick=function(){save(function(d){if(node.branchShared)delete d.nodes.find(function(n){return n.id===node.id;}).branchShared;else share(d,node.id);});};box.appendChild(button);if(node.branchShared){var shared=document.createElement('p');shared.textContent=t('✓ Этот блок — источник для следующих связанных блоков, включая новые.','✓ Цей блок — джерело для наступних пов’язаних блоків, включно з новими.');box.appendChild(shared);}
   (host.querySelector('[data-tab=visual]')||host).prepend(box);
 }
 w.ZargotaStoryBranch={resolve:resolve,source:source,share:share,enhance:enhance,batch:batch};
})(window);
