(function(w){
  'use strict';
  var STORAGE_KEY='zargota_story_editor_v1',activeKey='workshop-story',selectedNodeId='',selectedLinkId='',drag=null,sceneRecords=[],previewPages={};
  var workspaceTab='dialogues';
  var questsPending=false,stagePending=false,actorsPending=false,pointerPending=false,renderPending=false,releaseTimer=0;
  function releaseRender(){clearTimeout(releaseTimer);releaseTimer=setTimeout(function(){pointerPending=false;if(renderPending){renderPending=false;render();}if(actorsPending){actorsPending=false;openActors();}if(questsPending){questsPending=false;openQuests();}if(stagePending){stagePending=false;openStageSettings();}},0);}
  document.addEventListener('pointerdown',function(e){if(e.button===0&&e.target.closest('#zg-story-editor')){clearTimeout(releaseTimer);pointerPending=true;}},true);
  document.addEventListener('pointerup',releaseRender,true);document.addEventListener('pointercancel',releaseRender,true);w.addEventListener('blur',releaseRender);
  function showWorkspace(tab){
    workspaceTab=tab;var root=ensureUi();root.dataset.workspace=tab;
    if(w.ZargotaStoryStageEditor)w.ZargotaStoryStageEditor.close();if(w.ZargotaStoryActors)w.ZargotaStoryActors.close();
    root.querySelectorAll('[data-workspace-tab]').forEach(function(b){b.setAttribute('aria-pressed',String(b.dataset.workspaceTab===tab));});
    var pane=root.querySelector('.zg-story-workspace-pane');pane.querySelectorAll('.zg-quests-editor').forEach(function(e){e.remove();});if(tab==='quests'){captureScene();openQuests();}else if(tab==='scene'){captureScene();openStageSettings();}else if(tab==='actors'){captureScene();openActors();}
  }
  function embedPanel(id){var panel=document.getElementById(id),root=ensureUi();if(panel){panel.classList.add('zg-story-embedded');root.querySelector('.zg-story-workspace-pane').appendChild(panel);}}
  function uk(){return !!(w.ZargotaI18n&&w.ZargotaI18n.getLocale&&w.ZargotaI18n.getLocale()==='uk');}
  function t(ru,ua){return uk()?ua:ru;}
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(ch){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch];});}
  function uid(prefix){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6);}
  function local(value,key){if(key==='name'&&['Новий персонаж','Нова емоція'].includes(value.nameUk)&&value.name&&!['Новый персонаж','Новая эмоция'].includes(value.name))return String(value.name);return String(uk()&&value[key+'Uk']||value[key]||'');}
  function initialProject(){if(activeKey==='vrotik-prologue'&&w.ZargotaStoryPrologue)return JSON.parse(JSON.stringify(w.ZargotaStoryPrologue));if(activeKey==='vrotik-lookout-test'&&w.ZargotaStoryLookout)return JSON.parse(JSON.stringify(w.ZargotaStoryLookout));return activeKey==='vrotik-episode-1'&&w.ZargotaStoryCampaign?JSON.parse(JSON.stringify(w.ZargotaStoryCampaign)):seed();}
  function seed(){return{title:'Новый эпизод',titleUk:'Новий епізод',entryId:'dialog-1',activeSceneId:'',clockVisible:false,scene:{boardWidth:24,boardHeight:16,gridSize:64,layers:[],tokens:[],story:{}},nodes:[{id:'dialog-1',title:'Начало',titleUk:'Початок',speaker:'',text:'',x:70,y:70,links:[]}]};}
  function episodeOptions(){var all=loadAll();if(w.ZargotaStoryPrologue&&!all['vrotik-prologue'])all['vrotik-prologue']=w.ZargotaStoryPrologue;if(!all['workshop-story'])all['workshop-story']={title:'Свободный проект',titleUk:'Вільний проєкт'};if(!all['vrotik-episode-1'])all['vrotik-episode-1']=w.ZargotaStoryCampaign||{title:'Вротик · Эпизод 1',titleUk:'Вротік · Епізод 1'};return Object.keys(all).filter(function(key){return !all[key]._deleted;}).map(function(key){return '<option value="'+esc(key)+'">'+esc(local(all[key],'title')||key)+'</option>';}).join('');}
  function removeEpisode(key){
    var stored=loadAll(),fallback={'workshop-story':seed(),'vrotik-episode-1':w.ZargotaStoryCampaign,'vrotik-prologue':w.ZargotaStoryPrologue};
    var episode=stored[key]||fallback[key];if(!episode)return false;
    stored[key]=JSON.parse(JSON.stringify(episode));stored[key]._deleted=true;saveAll(stored);
    if(!loadAll()[key]?._deleted)return false;
    if(key===activeKey)switchProject(Object.keys(stored).find(function(id){return !stored[id]._deleted;})||uid('episode'));
    renderSceneControls();return true;
  }
  function episodeLibrary(){
    var old=document.getElementById('zg-story-episodes');if(old)old.remove();var dialog=document.createElement('dialog');dialog.id='zg-story-episodes';dialog.style.cssText='width:min(760px,90vw);max-height:85vh;overflow:auto;background:#111b19;color:#eadfc5;border:1px solid #698676;border-radius:12px;padding:24px';
    function action(label,fn){var b=document.createElement('button');b.type='button';b.textContent=label;b.style.cssText='padding:10px 16px;margin:6px';b.onclick=fn;return b;}
    var heading=document.createElement('h2');heading.textContent=t('Эпизоды','Епізоди');dialog.append(heading,action(t('Закрыть','Закрити'),function(){dialog.close();dialog.remove();}));
    var upload=document.createElement('input');upload.type='file';upload.accept='.json,application/json';upload.hidden=true;dialog.appendChild(upload);dialog.appendChild(action(t('↑ Загрузить JSON отдельной копией','↑ Завантажити JSON окремою копією'),function(){upload.click();}));var importStatus=document.createElement('p');importStatus.setAttribute('role','status');dialog.appendChild(importStatus);upload.onchange=async function(){var file=upload.files[0];if(!file)return;try{var doc=JSON.parse(await file.text()),draft=doc.episode;if(!draft||!Array.isArray(draft.nodes)||!draft.scene||!draft.nodes.every(function(n){return n&&typeof n.id==='string'&&Array.isArray(n.links);})||new Set(draft.nodes.map(function(n){return n.id;})).size!==draft.nodes.length)throw Error('invalid');captureScene();var records=loadAll(),key=uid('episode');records[key]=draft;saveAll(records);if(!loadAll()[key])throw Error('storage');switchProject(key);showWorkspace('scene');dialog.close();dialog.remove();}catch(error){importStatus.textContent=t('Не удалось загрузить эпизод. Проверьте JSON и свободное место. Текущая история сохранена.','Не вдалося завантажити епізод. Перевірте JSON і вільне місце. Поточну історію збережено.');}upload.value='';};
    var all=loadAll();all['workshop-story']=all['workshop-story']||seed();all['vrotik-episode-1']=all['vrotik-episode-1']||w.ZargotaStoryCampaign;all['vrotik-lookout-test']=all['vrotik-lookout-test']||w.ZargotaStoryLookout;all['vrotik-prologue']=all['vrotik-prologue']||w.ZargotaStoryPrologue;
    Object.keys(all).forEach(function(key){if(!all[key])return;if(all[key]._deleted){dialog.appendChild(action(t('Восстановить: ','Відновити: ')+local(all[key],'title'),function(){var stored=loadAll();delete stored[key]._deleted;saveAll(stored);dialog.close();episodeLibrary();}));return;}var row=document.createElement('div');row.className='zg-episode-row';var title=document.createElement('input');title.value=local(all[key],'title')||key;title.setAttribute('aria-label',t('Название эпизода','Назва епізоду'));title.maxLength=100;row.append(title,action(t('Сохранить название','Зберегти назву'),function(){if(!title.value.trim())return;var stored=loadAll();stored[key]=stored[key]||JSON.parse(JSON.stringify(all[key]));stored[key][uk()?'titleUk':'title']=title.value.trim();saveAll(stored);render();}),action(key===activeKey?t('Открыт','Відкрито'):t('Открыть','Відкрити'),function(){switchProject(key);showWorkspace('scene');dialog.close();dialog.remove();}));var armed=false;var remove=action(t('Удалить','Видалити'),function(){if(!armed){armed=true;remove.textContent=t('Подтвердить удаление','Підтвердити видалення');return;}var stored=loadAll();stored[key]=stored[key]||JSON.parse(JSON.stringify(all[key]));stored[key]._deleted=true;saveAll(stored);if(key===activeKey){activeKey=Object.keys(stored).find(function(k){return !stored[k]._deleted;})||uid('episode');project();if(w.zgStorySceneLoad)w.zgStorySceneLoad(project().scene);refreshStoryScenes(function(){showWorkspace('scene');});}dialog.close();episodeLibrary();});row.appendChild(remove);dialog.appendChild(row);});
    var form=document.createElement('form');form.style.marginTop='20px';var input=document.createElement('input');input.required=true;input.maxLength=100;input.placeholder=t('Название нового эпизода','Назва нового епізоду');input.setAttribute('aria-label',input.placeholder);input.style.cssText='width:65%;padding:12px';var create=document.createElement('button');create.textContent=t('Создать эпизод','Створити епізод');form.append(input,create);form.onsubmit=function(e){e.preventDefault();var title=input.value.trim();if(!title)return;captureScene();var records=loadAll(),key=uid('episode'),draft=seed();draft.title=title;draft.titleUk=title;records[key]=draft;saveAll(records);if(!loadAll()[key])return;switchProject(key);dialog.close();dialog.remove();};dialog.appendChild(form);document.body.appendChild(dialog);dialog.showModal();
  }
  function loadAll(){try{var value=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');if(w.ZargotaStoryAssets)value=w.ZargotaStoryAssets.repair(value);return value&&typeof value==='object'?value:{};}catch(error){return{};}}
  function saveAll(value){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(value));}catch(error){if(w.showToast)w.showToast(t('Не удалось сохранить сюжет: хранилище заполнено. Используйте ссылку на изображение вместо файла.','Не вдалося зберегти сюжет: сховище заповнене. Використайте посилання на зображення замість файлу.'));}}
  function addTabaxiHunter(data){
    if(!data||data.tabaxiHunterPortraitsV1)return false;
    data.speakers=data.speakers||{};
    var id=Object.keys(data.speakers).find(function(key){var speaker=data.speakers[key]||{};return ['Новый персонаж','Новий персонаж'].includes(speaker.nameUk||speaker.name)&&!speaker.portrait&&!Object.keys(speaker.emotions||{}).length;})||'tabaxi-hunter';
    if(!data.speakers[id]||!data.speakers[id].portrait)data.speakers[id]={name:'Табакси',nameUk:'Табакси',portrait:'assets/stories/portraits/Portraits/tabaxi-hunter/01_neutral.png',position:'50% 50%',zoom:1,emotions:{speaking:{name:'Говорит',nameUk:'Говорить',portrait:'assets/stories/portraits/Portraits/tabaxi-hunter/02_speaking.png',position:'50% 50%',zoom:1},angry:{name:'Злость',nameUk:'Злість',portrait:'assets/stories/portraits/Portraits/tabaxi-hunter/03_angry.png',position:'50% 50%',zoom:1},happy:{name:'Радость',nameUk:'Радість',portrait:'assets/stories/portraits/Portraits/tabaxi-hunter/04_happy.png',position:'50% 50%',zoom:1},sad:{name:'Грусть',nameUk:'Сум',portrait:'assets/stories/portraits/Portraits/tabaxi-hunter/05_sad.png',position:'50% 50%',zoom:1},thinking:{name:'Задумался',nameUk:'Замислився',portrait:'assets/stories/portraits/Portraits/tabaxi-hunter/06_thinking.png',position:'50% 50%',zoom:1}}};
    data.tabaxiHunterPortraitsV1=true;
    return true;
  }
  function addSatyrGirl(data){
    if(!data||data.satyrGirlPortraitsV1)return false;
    data.speakers=data.speakers||{};
    var id=Object.keys(data.speakers).find(function(key){var speaker=data.speakers[key]||{};return ['Новый персонаж','Новий персонаж'].includes(speaker.nameUk||speaker.name)&&!speaker.portrait&&!Object.keys(speaker.emotions||{}).length;})||'satyr-girl';
    if(!data.speakers[id]||!data.speakers[id].portrait)data.speakers[id]={name:'Сатир',nameUk:'Сатир',portrait:'assets/stories/portraits/Portraits/satyr-girl/01_neutral.png',position:'50% 50%',zoom:1,emotions:{speaking:{name:'Говорит',nameUk:'Говорить',portrait:'assets/stories/portraits/Portraits/satyr-girl/02_speaking.png',position:'50% 50%',zoom:1},angry:{name:'Злость',nameUk:'Злість',portrait:'assets/stories/portraits/Portraits/satyr-girl/03_angry.png',position:'50% 50%',zoom:1},happy:{name:'Радость',nameUk:'Радість',portrait:'assets/stories/portraits/Portraits/satyr-girl/04_happy.png',position:'50% 50%',zoom:1},sad:{name:'Грусть',nameUk:'Сум',portrait:'assets/stories/portraits/Portraits/satyr-girl/05_sad.png',position:'50% 50%',zoom:1},thinking:{name:'Задумалась',nameUk:'Замислилася',portrait:'assets/stories/portraits/Portraits/satyr-girl/06_thinking.png',position:'50% 50%',zoom:1}}};
    data.satyrGirlPortraitsV1=true;
    return true;
  }
  function addPortraitCharacter(data,marker,fallbackId,name,nameUk,folder){
    if(!data||data[marker])return false;
    data.speakers=data.speakers||{};
    var id=Object.keys(data.speakers).find(function(key){var speaker=data.speakers[key]||{};return ['Новый персонаж','Новий персонаж'].includes(speaker.nameUk||speaker.name)&&!speaker.portrait&&!Object.keys(speaker.emotions||{}).length;})||fallbackId;
    var base='assets/stories/portraits/Portraits/'+folder+'/';
    if(!data.speakers[id]||!data.speakers[id].portrait)data.speakers[id]={name:name,nameUk:nameUk,portrait:base+'01_neutral.png',position:'50% 50%',zoom:1,emotions:{speaking:{name:'Говорит',nameUk:'Говорить',portrait:base+'02_speaking.png',position:'50% 50%',zoom:1},angry:{name:'Злость',nameUk:'Злість',portrait:base+'03_angry.png',position:'50% 50%',zoom:1},happy:{name:'Радость',nameUk:'Радість',portrait:base+'04_happy.png',position:'50% 50%',zoom:1},sad:{name:'Грусть',nameUk:'Сум',portrait:base+'05_sad.png',position:'50% 50%',zoom:1},thinking:{name:'Задумался',nameUk:'Замислився',portrait:base+'06_thinking.png',position:'50% 50%',zoom:1}}};
    data[marker]=true;
    return true;
  }
  function addGuestPortraitCharacter(data,marker,fallbackId,name,nameUk,folder){
    if(!data||data[marker])return false;
    data.speakers=data.speakers||{};
    var id=Object.keys(data.speakers).find(function(key){var speaker=data.speakers[key]||{};return ['Новый персонаж','Новий персонаж'].includes(speaker.nameUk||speaker.name)&&!speaker.portrait&&!Object.keys(speaker.emotions||{}).length;})||fallbackId;
    var base='assets/stories/portraits/Portraits/'+folder+'/';
    if(!data.speakers[id]||!data.speakers[id].portrait)data.speakers[id]={name:name,nameUk:nameUk,portrait:base+'01_neutral.png',position:'50% 50%',zoom:1,emotions:{speaking:{name:'Говорит',nameUk:'Говорить',portrait:base+'02_speaking.png',position:'50% 50%',zoom:1}}};
    data[marker]=true;
    return true;
  }
  function project(){var all=loadAll();if(!all[activeKey]){all[activeKey]=initialProject();saveAll(all);}var data=all[activeKey],changed=addTabaxiHunter(data);if(addSatyrGirl(data))changed=true;if(addPortraitCharacter(data,'gnomeEngineerPortraitsV1','gnome-engineer','Гном-инженер','Гном-інженер','gnome-engineer'))changed=true;if(addPortraitCharacter(data,'settlementElderPortraitsV1','settlement-elder','Старейшина поселения','Старійшина поселення','settlement-elder'))changed=true;if(addPortraitCharacter(data,'goblinMessengerPortraitsV1','goblin-messenger','Гоблин-гонец','Гоблін-гонець','goblin-messenger'))changed=true;if(addPortraitCharacter(data,'karvenDragonbornPortraitsV1','karven-dragonborn','Карвен','Карвен','karven-dragonborn'))changed=true;if(addGuestPortraitCharacter(data,'fairyGuestPortraitsV1','fairy-guest','Фея-гостья','Фея-гостя','fairy-guest'))changed=true;if(addGuestPortraitCharacter(data,'myconidGuestPortraitsV1','myconid-guest','Миконид-музыкант','Міконід-музикант','myconid-guest'))changed=true;if(addGuestPortraitCharacter(data,'minotaurGuestPortraitsV1','minotaur-guest','Минотавр-пивовар','Мінотавр-бровар','minotaur-guest'))changed=true;if(activeKey==='vrotik-episode-1'&&w.ZargotaStoryCampaign){if(!data.walkable){data.walkable=JSON.parse(JSON.stringify(w.ZargotaStoryCampaign.walkable));changed=true;}(data.nodes||[]).forEach(function(node){var original=w.ZargotaStoryCampaign.nodes.find(function(n){return n.id===node.id;});if(node.complete==null&&original){node.complete=original.complete;changed=true;}});if(data.interactions&&data.interactions['story-brother']&&data.interactions['story-brother'].main==null){data.interactions['story-brother'].main=true;changed=true;}}if(changed)saveAll(all);return data;}
  function update(mutator,quiet){var restore=w.ZargotaStoryViewState?w.ZargotaStoryViewState.capture(document.getElementById("zg-story-editor")):function(){};var all=loadAll(),data=all[activeKey]||initialProject();mutator(data);if(data.activeSceneId){data.scenes=data.scenes||[];var current=data.scenes.find(function(r){return r.id===data.activeSceneId;});if(!current){current={id:data.activeSceneId};data.scenes.push(current);}current.name=data.scene.name||current.name||data.title;current.scene=JSON.parse(JSON.stringify(data.scene));sceneRecords=sceneRecords.map(function(r){return r.id===current.id?Object.assign({},r,current):r;});}all[activeKey]=data;saveAll(all);if(quiet)renderSceneControls();else render();restore();requestAnimationFrame(restore);}
  function captureScene(){/* The story draft is authoritative; workshop snapshots omit story-only fields. */}
  function switchProject(key){captureScene();activeKey=key;sceneRecords=[];selectedNodeId='';selectedLinkId='';var data=project();if(w.zgStorySceneLoad)w.zgStorySceneLoad(data.scene||null);applyChrome(true);render();refreshStoryScenes(function(){if(workspaceTab==='scene')openStageSettings();else if(workspaceTab==='actors')openActors();});}
  function openQuests(){w.ZargotaStoryQuests.edit(project(),function(fn){update(fn);if(pointerPending)questsPending=true;else openQuests();},ensureUi().querySelector('.zg-story-workspace-pane'));}function playProject(locationOnly,dialogueId,pageIndex,testQuestId){var workspace=document.getElementById('zg-story-editor'),savedTab=workspaceTab,savedScroll=Array.from(workspace.querySelectorAll('.zg-story-canvas,.zg-stage-fields,#zg-story-inspector')).map(function(e){return {selector:e.id?'#'+e.id:'.'+e.classList[0],x:e.scrollLeft,y:e.scrollTop};});captureScene();var data=project();data.scenes=sceneRecords.map(function(r){return {id:r.id,name:r.name,scene:r.id===data.activeSceneId?data.scene:r.scene};});if(locationOnly===true){data=JSON.parse(JSON.stringify(data));data.startSceneId=data.activeSceneId;data.intro={enabled:false};data.testLocation=true;if(dialogueId){data.testDialogueId=dialogueId;data.testDialoguePage=pageIndex||0;}var localNodes=w.ZargotaStoryLocationDialogues.nodes(data,data.activeSceneId),testQuest=(data.quests||[]).find(function(q){return localNodes.some(function(n){return n.id===q.dialogueId;});});if(testQuest)data.initialQuestId=testQuest.id;if(testQuestId!==undefined)data.initialQuestId=testQuestId;data.scene.tokens=data.scene.tokens||[];if(!data.scene.tokens.some(function(t){return t.id===data.heroTokenId;})){var hero=data.scenes.flatMap(function(r){return(r.scene||{}).tokens||[];}).find(function(t){return t.id===data.heroTokenId;});if(hero)data.scene.tokens.push(JSON.parse(JSON.stringify(hero)));}var selected=data.scenes.find(function(r){return r.id===data.activeSceneId;});if(selected)selected.scene=data.scene;}if(!data.heroTokenId||!(data.scene.tokens||[]).some(function(token){return token.id===data.heroTokenId;})){if(w.showToast)w.showToast(t('Выберите или создайте токен игрока в «Герой и портреты».','Оберіть або створіть токен гравця в «Герой та портрети».'));return;}w.zgStoryEditorClose();if(w.ZargotaStoryPlayer)w.ZargotaStoryPlayer.start(data,function(){w.zgStoryEditorOpen(activeKey);refreshStoryScenes(function(){showWorkspace(savedTab);requestAnimationFrame(function(){savedScroll.forEach(function(s){var e=workspace.querySelector(s.selector);if(e){e.scrollLeft=s.x;e.scrollTop=s.y;}});});});});}
  function campaignToolbar(root){
    var bar=document.createElement('div');bar.className='zg-story-campaign-controls';
    var library=document.createElement('button');library.type='button';library.textContent=t('▤ Эпизоды','▤ Епізоди');library.onclick=episodeLibrary;bar.appendChild(library);
    var select=document.createElement('select');select.dataset.storyProjectSelect='';select.storyDeleteOption=removeEpisode;select.setAttribute('aria-label',t('Сюжет кампании','Сюжет кампанії'));select.innerHTML='<option value="workshop-story">'+esc(t('Свободный проект','Вільний проєкт'))+'</option><option value="vrotik-episode-1">'+esc(t('Вротик · Эпизод 1','Вротік · Епізод 1'))+'</option>';select.value=activeKey;select.onchange=function(){switchProject(this.value);};bar.appendChild(select);
    var play=document.createElement('button');play.type='button';play.textContent='▶ '+t('Пройти эпизод','Пройти епізод');play.onclick=function(){playProject(false);};var enter=document.createElement('button');enter.type='button';enter.textContent=t('▶ Зайти на локацию','▶ Зайти на локацію');enter.title=t('Тест выбранной локации: прежние условия пропускаются, сохранения не меняются','Тест обраної локації: попередні умови пропускаються, збереження не змінюються');enter.onclick=function(){w.ZargotaStoryTestEntry.choose(project(),function(id){playProject(true,null,0,id);});};
    var download=document.createElement('button');download.type='button';download.textContent=t('↓ Экспорт эпизода · JSON','↓ Експорт епізоду · JSON');download.onclick=function(){captureScene();refreshStoryScenes(function(){try{var json=w.ZargotaStoryAssets.exportEpisode(project(),sceneRecords),url=URL.createObjectURL(new Blob([json],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=activeKey+'.json';a.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);}catch(e){if(w.showToast)w.showToast(t('В эпизоде есть встроенные или временные медиа. Сначала замените их путями из папки ресурсов.','В епізоді є вбудовані або тимчасові медіа. Спочатку замініть їх шляхами з папки ресурсів.'));}});};bar.appendChild(download);
    var tabs=document.createElement('nav');tabs.className='zg-story-workspace-tabs';[['scene',t('▧ Карта','▧ Карта')],['dialogues',t('◇ Диалоги','◇ Діалоги')],['actors',t('♙ Персонажи','♙ Персонажі')],['quests',t('✧ Задания','✧ Завдання')]].forEach(function(pair){var b=document.createElement('button');b.type='button';b.textContent=pair[1];b.dataset.workspaceTab=pair[0];b.onclick=function(){showWorkspace(pair[0]);};tabs.appendChild(b);});bar.append(play,enter);root.querySelector('.zg-story-head').after(bar);bar.after(tabs);root.querySelector('.zg-story-head').prepend(bar);var rail=document.createElement('aside');rail.className='zg-story-location-rail';rail.setAttribute('aria-label',t('Локации эпизода','Локації епізоду'));root.appendChild(rail);var pane=document.createElement('div');pane.className='zg-story-workspace-pane';root.appendChild(pane);root.dataset.workspace=workspaceTab;tabs.querySelector('[data-workspace-tab="dialogues"]').setAttribute('aria-pressed','true');
  }
  function enhanceInspector(data){
    var host=document.getElementById('zg-story-inspector'),node=nodeById(data,selectedNodeId);if(!host||!node)return;
    var playback=document.createElement('div'),moment=document.createElement('select'),run=document.createElement('button');playback.className='zg-story-play-from';moment.setAttribute('aria-label',t('Начать с реплики','Почати з репліки'));[node].concat(node.slides||[]).forEach(function(page,i){var option=document.createElement('option');option.value=i;option.textContent=(i+1)+'. '+(local(page,'text').slice(0,70)||local(node,'title'));moment.appendChild(option);});var momentKey=activeKey+':'+node.id;moment.value=String(Math.min((node.slides||[]).length,previewPages[momentKey]||0));moment.onchange=function(){previewPages[momentKey]=Number(moment.value);};run.type='button';run.textContent=t('▶ Проиграть с этой реплики','▶ Програти з цієї репліки');run.onclick=function(){playProject(true,node.id,Number(moment.value));};playback.append(moment,run);host.appendChild(playback);var speaker=host.querySelector('[data-story-field="speaker"]');
    var connect=document.createElement('button');connect.type='button';connect.textContent=t('＋ Создать следующую реплику','＋ Створити наступну репліку');connect.onclick=function(){update(function(next){var parent=nodeById(next,node.id),id=uid('dialog');if(!parent)return;next.nodes.push({id:id,editorSceneId:next.activeSceneId||'',title:'Новая реплика',titleUk:'Нова репліка',text:'',textUk:'',speaker:parent.speaker||'',x:(Number(parent.x)||0)+280,y:Number(parent.y)||70,links:[]});parent.links=parent.links||[];parent.links.push({id:uid('line'),to:id,label:'',labelUk:'',delayMs:0});selectedNodeId=id;});};host.appendChild(connect);
    var binding=document.createElement('label');binding.className='zg-story-field';binding.textContent=t('Начать эту реплику при нажатии на объект','Почати цю репліку після натискання на об’єкт');var target=document.createElement('select');target.innerHTML='<option value="">'+esc(t('Выбрать объект…','Обрати об’єкт…'))+'</option>'+(data.scene&&data.scene.tokens||[]).filter(function(token){return token.id!==data.heroTokenId;}).map(function(token){return'<option value="'+esc(token.id)+'">'+esc(local(token,'name'))+'</option>';}).join('');target.onchange=function(){if(!this.value)return;var id=this.value;update(function(next){next.interactions=next.interactions||{};next.interactions[id]={entryId:node.id,marker:'?'};});};binding.appendChild(target);host.appendChild(binding);
    var media=document.createElement('fieldset');media.className='zg-story-extra';media.innerHTML='<legend>'+esc(t('Осмотр · изображение и реплика','Огляд · зображення та репліка'))+'</legend><p>'+esc(t('Без изображения показывается обычный диалог. С изображением — вид от первого лица на весь экран.','Без зображення показується звичайний діалог. Із зображенням — вигляд від першої особи на весь екран.'))+'</p><label class="zg-story-field"><span>'+esc(t('Путь или URL изображения','Шлях або URL зображення'))+'</span><input data-story-extra="image" value="'+esc(node.image||'')+'"></label><label class="zg-story-field"><span>'+esc(t('Загрузить изображение (до 2 МБ)','Завантажити зображення (до 2 МБ)'))+'</span><input type="file" accept="image/png,image/jpeg,image/webp" data-story-upload></label>'+(node.image?'<img class="zg-story-media-preview" src="'+esc(node.image)+'" alt="'+esc(t('Предпросмотр осмотра','Попередній перегляд огляду'))+'"><button type="button" data-story-clear-image>'+esc(t('Убрать изображение','Прибрати зображення'))+'</button>':'');host.appendChild(media);
    host.querySelectorAll('.zg-story-link-row').forEach(function(row,index){var link=node.links[index];var title=document.createElement('strong');title.className='zg-story-edge-title';title.textContent=link.id;row.prepend(title);[['link-to',t('Следующая реплика','Наступна репліка')],['link-delay',t('Задержка, мс','Затримка, мс')],['link-label',t('Текст выбора (пусто — продолжить)','Текст вибору (порожньо — продовжити)')]].forEach(function(pair){var input=row.querySelector('[data-story-field="'+pair[0]+'"]');if(!input)return;var label=document.createElement('label');label.className='zg-story-field';label.textContent=pair[1];input.before(label);label.appendChild(input);input.style.gridColumn='';});['effect','requires'].forEach(function(key){var label=document.createElement('label');label.className='zg-story-field';label.textContent=key==='effect'?t('Последствие: установить флаг','Наслідок: установити прапорець'):t('Показывать, если установлен флаг','Показувати, якщо встановлено прапорець');var input=document.createElement('input');input.value=link[key]||'';input.dataset.storyExtra=key;input.dataset.edgeId=link.id;input.placeholder=key==='effect'?'stone_examined':'stone_examined';label.appendChild(input);row.appendChild(label);});});
    var replay=document.createElement('fieldset');replay.className='zg-graph-advanced';var replayLegend=document.createElement('legend');replayLegend.textContent=t('Повторное взаимодействие','Повторна взаємодія');replay.appendChild(replayLegend);
    var replayLabel=document.createElement('label');replayLabel.className='zg-story-field';replayLabel.textContent=t('После завершения разговора','Після завершення розмови');var replayMode=document.createElement('select');[[ 'same',t('Повторять этот диалог','Повторювати цей діалог')],[ 'once',t('Больше не запускать','Більше не запускати')],[ 'alternate',t('Запускать другой диалог','Запускати інший діалог')]].forEach(function(pair){var option=document.createElement('option');option.value=pair[0];option.textContent=pair[1];replayMode.appendChild(option);});replayMode.value=node.replayMode||(node.repeatWhen&&node.repeatId?'alternate':'same');replayMode.onchange=function(){update(function(d){var n=nodeById(d,node.id);if(!n)return;n.replayMode=replayMode.value;delete n.repeatWhen;if(replayMode.value!=='alternate')delete n.repeatId;});};replayLabel.appendChild(replayMode);replay.appendChild(replayLabel);
    var repeatLabel=document.createElement('label');repeatLabel.className='zg-story-field';repeatLabel.textContent=t('Диалог для следующих взаимодействий','Діалог для наступних взаємодій');var repeatTarget=document.createElement('select'),emptyRepeat=document.createElement('option');emptyRepeat.value='';emptyRepeat.textContent=t('Выберите начальную реплику…','Оберіть початкову репліку…');repeatTarget.appendChild(emptyRepeat);(data.nodes||[]).filter(function(n){return n.id!==node.id;}).forEach(function(n){var option=document.createElement('option');option.value=n.id;option.textContent=(local(n,'title')||n.id)+' ['+n.id+']';repeatTarget.appendChild(option);});repeatTarget.value=node.repeatId||'';repeatTarget.onchange=function(){update(function(d){var n=nodeById(d,node.id);if(!n)return;n.replayMode='alternate';n.repeatId=repeatTarget.value;delete n.repeatWhen;});};repeatLabel.appendChild(repeatTarget);repeatLabel.hidden=replayMode.value!=='alternate';replay.appendChild(repeatLabel);var replayNote=document.createElement('p');replayNote.className='zg-story-note';replayNote.textContent=t('Режим меняется только после кнопки «Завершить разговор». Флаги для этого не нужны.','Режим змінюється лише після кнопки «Завершити розмову». Прапорці для цього не потрібні.');replay.appendChild(replayNote);host.appendChild(replay);
    if(w.ZargotaStoryAssets)w.ZargotaStoryAssets.attach(host.querySelector('[data-story-extra="image"]'),'image');
    var note=document.createElement('p');note.className='zg-story-note';note.textContent=t('Флаги действуют в текущем прохождении и сбрасываются при запуске заново. Несколько линий создают выбор.','Прапорці діють у поточному проходженні та скидаються під час запуску заново. Кілька ліній створюють вибір.');host.appendChild(note);
    if(speaker){var select=document.createElement('select');select.dataset.storyField='speaker';[['',t('Без имени','Без імені')],['@player',t('♙ Персонаж игрока','♙ Персонаж гравця')]].forEach(function(p){var o=document.createElement('option');o.value=p[0];o.textContent=p[1];select.appendChild(o);});Object.keys(data.speakers||{}).filter(function(key){return !data.speakers[key].archived||key===node.speaker;}).forEach(function(key){var opt=document.createElement('option');opt.value=key;opt.textContent=local(data.speakers[key],'name');select.appendChild(opt);});if(node.speaker&&node.speaker!=='@player'&&!(data.speakers||{})[node.speaker]){var extra=document.createElement('option');extra.value=node.speaker||'';extra.textContent=node.speaker||t('Рассказчик','Оповідач');select.appendChild(extra);}select.value=node.speaker; speaker.replaceWith(select);}
    var section=document.createElement('div');section.className='zg-story-project-fields';section.innerHTML='<h3>'+esc(t('Задание эпизода','Завдання епізоду'))+'</h3>'+['quest','objective'].map(function(key){return'<label class="zg-story-field"><span>'+esc(key==='quest'?t('Название задания','Назва завдання'):t('Цель задания','Мета завдання'))+'</span><input data-story-field="'+key+'" value="'+esc(local(data,key))+'"></label>';}).join('')+'<label class="zg-story-field"><span><input type="checkbox" data-story-field="complete"'+(node.complete?' checked':'')+' style="width:auto"> '+esc(t('Эта реплика завершает задание','Ця репліка завершує завдання'))+'</span></label>';if(!(data.quests||[]).length)host.appendChild(section);if(w.ZargotaStoryStageEditor)w.ZargotaStoryStageEditor.enhance(data,node,host,update,sceneRecords);if(w.ZargotaStoryActors)w.ZargotaStoryActors.enhance(data,node,host,update);if(w.ZargotaStorySequence)w.ZargotaStorySequence.enhance(data,node,host,update);
  }
  var baseEnhanceInspector=enhanceInspector;
  enhanceInspector=function(data){baseEnhanceInspector(data);if(w.ZargotaStoryGraph)w.ZargotaStoryGraph.decorate(data,selectedNodeId);var n=nodeById(data,selectedNodeId);if(n&&w.ZargotaStoryBranch)w.ZargotaStoryBranch.enhance(data,n,document.getElementById('zg-story-inspector'),update);if(n&&w.ZargotaStoryPages)w.ZargotaStoryPages.enhance(data,n,document.getElementById('zg-story-inspector'),update);if(n&&w.ZargotaStoryScreenFx)w.ZargotaStoryScreenFx.enhance(data,n,document.getElementById('zg-story-inspector'),update);if(n&&w.ZargotaStoryBranchView)w.ZargotaStoryBranchView.decorate(data,n,document.getElementById('zg-story-inspector'));if(n&&w.ZargotaStoryAIDialogues)w.ZargotaStoryAIDialogues.decorate(data,n,document.getElementById('zg-story-inspector'),update);if(n&&w.ZargotaStoryDialogueActions)w.ZargotaStoryDialogueActions.edit(data,n,document.querySelector('#zg-story-inspector [data-tab=events]'),update);if(n&&w.ZargotaStoryAudioEditor)w.ZargotaStoryAudioEditor.edit(data,n.musicEvent,document.querySelector('#zg-story-inspector [data-tab=events]'),function(v){update(function(d){d.nodes.find(function(x){return x.id===n.id;}).musicEvent=v;});});};
  function nodeById(data,id){return(data.nodes||[]).find(function(node){return node.id===id;})||null;}
  function ensureUi(){
    var root=document.getElementById('zg-story-editor');if(root)return root;
    root=document.createElement('section');root.id='zg-story-editor';root.className='zg-story-editor';root.setAttribute('role','dialog');root.setAttribute('aria-label',t('Редактор сюжетных диалогов','Редактор сюжетних діалогів'));
    root.innerHTML='<header class="zg-story-head"><span><strong id="zg-story-heading"></strong><small id="zg-story-project"></small></span><div class="zg-story-scene-controls"><select data-story-scenes aria-label="'+esc(t('Сюжетная сцена','Сюжетна сцена'))+'"></select><button type="button" data-story-new-scene></button><button type="button" data-story-save-scene></button><button type="button" data-story-clock></button></div><div class="zg-story-head-actions"><button type="button" data-story-add></button><button type="button" data-story-scene></button><button type="button" data-story-close>×</button></div></header><div class="zg-story-body"><div class="zg-story-canvas"><div class="zg-story-stage" id="zg-story-stage"><svg class="zg-story-links" id="zg-story-links" viewBox="0 0 1200 760" preserveAspectRatio="none"></svg><div id="zg-story-nodes"></div></div></div><aside class="zg-story-inspector" id="zg-story-inspector"></aside></div>';
    document.body.appendChild(root);
    if(w.ZargotaStoryGraph)w.ZargotaStoryGraph.install(root,{get:project,update:update,selectedLink:function(){return selectedLinkId;},select:function(id){selectedNodeId=id;selectedLinkId='';}});
    campaignToolbar(root);
    if(w.ZargotaStoryAIDialogues)w.ZargotaStoryAIDialogues.install(root,{get:project,update:update,select:function(id){selectedNodeId=id;selectedLinkId='';}});
    if(w.ZargotaStoryFragments)w.ZargotaStoryFragments.install(root,{get:project,update:update});
    if(w.ZargotaStoryTimelineEditor)w.ZargotaStoryTimelineEditor.install(root,{get:project,update:update});
    if(w.ZargotaStoryGraphSelection)w.ZargotaStoryGraphSelection.install(root,{get:project,update:update});
    document.addEventListener('keydown',function(e){if((e.key==='Delete'||e.key==='Backspace')&&root.classList.contains('open')&&workspaceTab==='dialogues'&&selectedLinkId&&!e.target.closest('input,textarea,select,[contenteditable=true]')&&!(e.target.closest('[role=dialog],dialog')&&!root.contains(e.target))){e.preventDefault();removeLink(selectedLinkId);}});
    root.querySelector('[data-story-add]').onclick=addNode;
    root.querySelector('[data-story-scene]').onclick=function(){w.zgStoryEditorClose();if(w.zgSceneSettings)w.zgSceneSettings();};
    root.querySelector('[data-story-new-scene]').onclick=newStoryScene;
    root.querySelector('[data-story-save-scene]').onclick=saveStoryScene;
    root.querySelector('[data-story-clock]').onclick=toggleClock;
    root.querySelector('[data-story-scenes]').onchange=function(){loadStoryScene(this.value);};
    root.querySelector('[data-story-close]').onclick=w.zgStoryEditorClose;
    root.addEventListener('change',fieldInput);root.addEventListener('click',click);
    root.addEventListener('change',function(event){var el=event.target,key=el.dataset.storyExtra,id=selectedNodeId;if(el.hasAttribute('data-story-upload')){var file=el.files[0];if(!file)return;if(file.size>2*1024*1024||!/^image\/(png|jpeg|webp)$/.test(file.type)){if(w.showToast)w.showToast(t('Выберите PNG, JPEG или WebP до 2 МБ','Оберіть PNG, JPEG або WebP до 2 МБ'));return;}var reader=new FileReader();reader.onload=function(){update(function(data){var node=nodeById(data,id);if(node)node.image=reader.result;});};reader.readAsDataURL(file);return;}if(!key)return;update(function(data){var node=nodeById(data,id);if(!node)return;if(key==='image'){node.image=el.value.trim();return;}var edge=node.links.find(function(link){return link.id===el.dataset.edgeId;});if(edge)edge[key]=el.value.trim();});});
    root.addEventListener('click',function(event){if(event.target.closest('[data-story-clear-image]'))update(function(data){var node=nodeById(data,selectedNodeId);if(node)node.image='';});});
    root.addEventListener('pointerdown',pointerDown);document.addEventListener('pointermove',pointerMove);document.addEventListener('pointerup',pointerUp);
    return root;
  }
  function applyChrome(enabled){var overlay=document.getElementById('zg-game-overlay'),data=project();if(!overlay)return;overlay.classList.toggle('story-mode',!!enabled);overlay.classList.toggle('story-clock-visible',!!enabled&&data.clockVisible===true);}
  function refreshStoryScenes(done){if(!w.ZargotaLib||!w.ZargotaLib.list){sceneRecords=(project().scenes||[]).slice();renderSceneControls();if(done)done();return;}w.ZargotaLib.list('story-scene',function(items){sceneRecords=(Array.isArray(items)?items:[]).filter(function(item){return item.projectId===activeKey||(!item.projectId&&activeKey==='workshop-story');}).sort(function(a,b){return Number(a.created||0)-Number(b.created||0);});var merged=new Map(sceneRecords.map(function(r){return[r.id,r];}));(project().scenes||[]).forEach(function(r){merged.set(r.id,r);});sceneRecords=Array.from(merged.values());render();renderSceneControls();if(done)done();});}
  function renderSceneControls(){var root=document.getElementById('zg-story-editor');if(!root)return;var projects=root.querySelector('[data-story-project-select]');if(projects){projects.innerHTML=episodeOptions();projects.value=activeKey;}var data=project(),select=root.querySelector('[data-story-scenes]');var opened=sceneRecords.find(function(r){return r.id===data.activeSceneId;});var sceneName=data.scene&&data.scene.name||opened&&opened.name||local(data,'title');root.querySelector('#zg-story-heading').textContent=sceneName;if(select)select.innerHTML=(!opened?'<option value="" disabled selected>'+esc(sceneName+' · '+t('текущая','поточна'))+'</option>':'')+sceneRecords.map(function(record,index){return'<option value="'+esc(record.id)+'"'+(record.id===data.activeSceneId?' selected':'')+'>'+esc((index+1)+'. '+(record.id===data.activeSceneId?sceneName:record.name))+'</option>';}).join('');var rail=root.querySelector('.zg-story-location-rail');if(rail){rail.replaceChildren();var label=document.createElement('h3');label.textContent=t('Локации','Локації');rail.appendChild(label);var records=sceneRecords.slice();if(!opened)records.unshift({id:'',name:sceneName,scene:data.scene});records.forEach(function(r,i){var b=document.createElement('button');b.type='button';b.setAttribute('aria-pressed',String(r.id===(data.activeSceneId||'')));var img=document.createElement('img');img.alt='';img.src=((r.scene||{}).layers||[])[0]?.image||'';if(img.src)b.appendChild(img);var text=document.createElement('span');text.textContent=(i+1)+'. '+(local(r.scene||{},'name')||r.name||sceneName);b.appendChild(text);b.onclick=function(){var tab=workspaceTab;if(r.id)loadStoryScene(r.id);showWorkspace(tab);};rail.appendChild(b);});var add=document.createElement('button');add.textContent=t('＋ Локация','＋ Локація');add.onclick=newStoryScene;rail.appendChild(add);var settingsTitle=document.createElement('h3');settingsTitle.textContent=t('Настройки эпизода','Налаштування епізоду');settingsTitle.style.marginTop='24px';rail.appendChild(settingsTitle);[['▷ '+t('Заставка','Заставка'),function(){captureScene();w.ZargotaStoryIntro.edit(project(),update);}],['☷ '+t('Панель героя','Панель героя'),function(){captureScene();w.ZargotaStoryHud.edit(project(),update);}]].forEach(function(p){var b=document.createElement('button');b.type='button';b.textContent=p[0];b.onclick=p[1];rail.appendChild(b);});}var newButton=root.querySelector('[data-story-new-scene]'),saveButton=root.querySelector('[data-story-save-scene]'),clockButton=root.querySelector('[data-story-clock]');if(newButton)newButton.textContent='＋ '+t('Новая локация','Нова локація');if(saveButton)saveButton.textContent='💾 '+t('Сохранить','Зберегти');if(clockButton){clockButton.textContent='◷ '+t('Дата','Дата')+': '+(data.clockVisible?t('вкл','увімк'):t('выкл','вимк'));clockButton.classList.toggle('active',data.clockVisible===true);}}
  function loadStoryScene(id){id=String(id||'');if(!id)return;var data=project(),record=sceneRecords.find(function(item){return item.id===id;});function apply(found){if(!found||!found.scene)return;if(found.id===data.activeSceneId){renderSceneControls();return;}if(!data.activeSceneId){var draftId='scene-'+Date.now().toString(36)+'-draft';update(function(next){next.activeSceneId=draftId;});var draft=project().scenes.find(function(r){return r.id===draftId;});if(draft)sceneRecords.push(draft);}if(workspaceTab==='scene'&&w.zgStorySceneLoad)w.zgStorySceneLoad(found.scene);update(function(next){next.activeSceneId=found.id;next.scene=JSON.parse(JSON.stringify(found.scene));});if(workspaceTab==='scene')openStageSettings();}if(record)apply(record);else if(w.ZargotaLib&&w.ZargotaLib.get)w.ZargotaLib.get(id,apply);}
  function loadRememberedStoryScene(){var data=project();if(!data.activeSceneId){renderSceneControls();return;}if(!w.ZargotaLib||!w.ZargotaLib.get)return;w.ZargotaLib.get(data.activeSceneId,function(record){if(record&&record.category==='story-scene'&&record.scene&&w.zgStorySceneLoad)w.zgStorySceneLoad(record.scene);});}
  function saveStoryScene(){if(!w.ZargotaLib||!w.ZargotaLib.put||!w.zgStorySceneSnapshot)return;var data=project(),scene=JSON.parse(JSON.stringify(data.scene||{})),existing=sceneRecords.find(function(item){return item.id===data.activeSceneId;}),now=Date.now(),record=existing?Object.assign({},existing):{id:'story-'+now.toString(36)+'-'+Math.random().toString(36).slice(2,6),category:'story-scene',created:now};record.category='story-scene';record.projectId=activeKey;record.name=scene.name||record.name||data.title+' · '+t('Сцена ','Сцена ')+(sceneRecords.length+1);scene.story=data.scene&&data.scene.story||{};record.scene=scene;record.updatedAt=now;w.ZargotaLib.put(record,function(saved){if(!saved)return;update(function(next){next.activeSceneId=saved.id;next.scene=scene;});refreshStoryScenes();if(w.showToast)w.showToast(t('Сюжетная сцена сохранена отдельно от игровых сцен','Сюжетну сцену збережено окремо від ігрових сцен'));});}
  function newStoryScene(){w.ZargotaStoryMenus.createScene(function(name){update(function(data){data.scenes=data.scenes||[];var oldId=data.activeSceneId||'scene-'+Date.now().toString(36);var old=data.scenes.find(function(r){return r.id===oldId;});if(!old){old={id:oldId};data.scenes.push(old);}old.name=data.scene.name||data.title;old.scene=JSON.parse(JSON.stringify(data.scene));data.activeSceneId='scene-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6);data.scene={name:name,boardWidth:24,boardHeight:16,gridSize:64,layers:[],tokens:[],story:{}};});refreshStoryScenes(function(){openStageSettings();});});}
  function openActors(){if(w.ZargotaStoryActors){w.ZargotaStoryActors.open(project(),function(fn){update(fn);if(pointerPending)actorsPending=true;else openActors();},activeKey);embedPanel('zg-story-actors');}}
  function openStageSettings(){if(w.ZargotaStoryStageEditor){w.ZargotaStoryStageEditor.open(project(),function(fn,options){update(fn,options&&options.quiet);if(options&&options.quiet)return;if(w.zgStorySceneLoad)w.zgStorySceneLoad(project().scene);if(pointerPending)stagePending=true;else openStageSettings();},sceneRecords);embedPanel('zg-story-stage-settings');}}
  function toggleClock(){update(function(data){data.clockVisible=!data.clockVisible;});applyChrome(true);}
  function addNode(){update(function(data){var count=(data.nodes||[]).length+1,id='dialog-'+count;while(nodeById(data,id))id=uid('dialog');data.nodes.push({id:id,editorSceneId:data.activeSceneId||'',title:t('Реплика '+count,'Репліка '+count),speaker:'',text:'',x:70+((count-1)%4)*270,y:70+Math.floor((count-1)/4)*170,links:[]});selectedNodeId=id;selectedLinkId='';});}
  function addLink(){update(function(data){var node=nodeById(data,selectedNodeId),target=(data.nodes||[]).find(function(item){return item.id!==selectedNodeId;});if(!node)return;var used={};(data.nodes||[]).forEach(function(item){(item.links||[]).forEach(function(link){used[link.id]=true;});});var number=1;while(used['line-'+number])number+=1;node.links=node.links||[];var link={id:'line-'+number,to:target?target.id:'',label:'',delayMs:0};node.links.push(link);selectedLinkId=link.id;});}
  function removeLink(id){update(function(data){var node=nodeById(data,selectedNodeId),link=node&&(node.links||[]).find(function(link){return link.id===id;});if(link){link.to='';delete link.sceneId;}selectedLinkId='';});}
  function removeNode(){update(function(data){if((data.nodes||[]).length<2)return;data.nodes=data.nodes.filter(function(node){return node.id!==selectedNodeId;});data.nodes.forEach(function(node){node.links=(node.links||[]).filter(function(link){return link.to!==selectedNodeId;});});if(data.entryId===selectedNodeId)data.entryId=data.nodes[0].id;selectedNodeId=data.nodes[0].id;selectedLinkId='';});}
  function fieldInput(event){var el=event.target,key=el.getAttribute('data-story-field');if(!key)return;update(function(data){var node=nodeById(data,selectedNodeId);if(!node)return;if(key==='entry'){data.entryId=el.value;return;}if(key==='quest'||key==='objective'){data[uk()?key+'Uk':key]=el.value;return;}if(key==='complete'){node.complete=el.checked;return;}if(key==='title'||key==='speaker'||key==='text'){node[key==='speaker'?key:uk()?key+'Uk':key]=el.value;return;}var linkId=el.getAttribute('data-link-id'),link=(node.links||[]).find(function(item){return item.id===linkId;});if(!link)return;if(key==='link-to')link.to=el.value;if(key==='link-label')link[uk()?'labelUk':'label']=el.value;if(key==='link-delay')link.delayMs=Math.max(0,Number(el.value)||0);});}
  function click(event){var nodeEl=event.target.closest('.zg-story-node');if(nodeEl){selectedNodeId=nodeEl.getAttribute('data-node-id');selectedLinkId='';render();return;}var linkEl=event.target.closest('[data-story-link]');if(linkEl){selectedLinkId=linkEl.getAttribute('data-story-link');var from=linkEl.getAttribute('data-from');if(from)selectedNodeId=from;render();return;}if(event.target.closest('[data-story-add-link]')){addLink();return;}var remove=event.target.closest('[data-story-remove-link]');if(remove){removeLink(remove.getAttribute('data-story-remove-link'));return;}if(event.target.closest('[data-story-remove-node]'))removeNode();}
  function pointerDown(event){var card=event.target.closest('.zg-story-node');if(event.button!==0||!card||event.target.closest('button,input,textarea,select'))return;var data=project(),node=nodeById(data,card.getAttribute('data-node-id'));if(!node)return;selectedNodeId=node.id;selectedLinkId='';drag={id:event.pointerId,nodeId:node.id,startX:event.clientX,startY:event.clientY,x:Number(node.x)||0,y:Number(node.y)||0,data:data,moved:false,frame:0};drag.data=Object.assign({},data,{nodes:w.ZargotaStoryLocationDialogues?w.ZargotaStoryLocationDialogues.nodes(data,data.activeSceneId||''):data.nodes});try{card.setPointerCapture(event.pointerId);}catch(error){}event.preventDefault();}
  function pointerMove(event){if(!drag||event.pointerId!==drag.id)return;if(!drag.moved&&Math.hypot(event.clientX-drag.startX,event.clientY-drag.startY)<3)return;drag.moved=true;var card=document.querySelector('.zg-story-node[data-node-id="'+drag.nodeId+'"]');if(!card)return;var scale=w.ZargotaStoryGraph?w.ZargotaStoryGraph.scale:1,left=Math.max(12,drag.x+(event.clientX-drag.startX)/scale),top=Math.max(12,drag.y+(event.clientY-drag.startY)/scale);card.style.left=left+'px';card.style.top=top+'px';var node=nodeById(drag.data,drag.nodeId);if(node){node.x=left;node.y=top;if(!drag.frame)drag.frame=requestAnimationFrame(function(){if(!drag)return;drag.frame=0;drawLinks(drag.data);});}event.preventDefault();}
  function pointerUp(event){if(!drag||event.pointerId!==drag.id)return;cancelAnimationFrame(drag.frame);if(!drag.moved){drag=null;return;}var nodeId=drag.nodeId,card=document.querySelector('.zg-story-node[data-node-id="'+nodeId+'"]'),left=card?parseFloat(card.style.left):drag.x,top=card?parseFloat(card.style.top):drag.y;drag=null;update(function(data){var node=nodeById(data,nodeId);if(node){node.x=Math.max(12,left||0);node.y=Math.max(12,top||0);}});}
  function linkMarkup(data,node,link){var to=nodeById(data,link.to);if(!to&&link.sceneId)to={x:(Number(node.x)||0)+300,y:(Number(node.y)||0)+(node.links||[]).indexOf(link)*40};if(!to)return'';var x1=(Number(node.x)||0)+220,y1=(Number(node.y)||0)+52,x2=Number(to.x)||0,y2=(Number(to.y)||0)+52,curve=Math.max(50,Math.abs(x2-x1)*.45),path='M '+x1+' '+y1+' C '+(x1+curve)+' '+y1+' '+(x2-curve)+' '+y2+' '+x2+' '+y2,label=link.id+(local(link,'label')?' · '+local(link,'label'):'')+(link.sceneId?' ↗ '+((sceneRecords.find(function(s){return s.id===link.sceneId;})||{}).name||link.sceneId):''),delay=Math.max(0,Number(link.delayMs)||0);return'<path class="zg-story-link'+(link.id===selectedLinkId?' selected':'')+'" data-story-link="'+esc(link.id)+'" data-from="'+esc(node.id)+'" d="'+path+'"></path><text class="zg-story-link-label" x="'+((x1+x2)/2)+'" y="'+(((y1+y2)/2)-7)+'" text-anchor="middle">'+esc(label+(delay?' · '+delay+' мс':''))+'</text>';}
  function drawLinks(data){if(w.ZargotaStoryGraph){w.ZargotaStoryGraph.edges(data);return;}var svg=document.getElementById('zg-story-links');if(!svg)return;svg.innerHTML='<defs><marker id="zg-story-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#6a9f91"></path></marker></defs>'+(data.nodes||[]).map(function(node){return(node.links||[]).map(function(link){return linkMarkup(data,node,link);}).join('');}).join('');}
  function inspector(data,node){if(!node)return'<div class="zg-story-empty">'+esc(t('Выберите реплику на схеме','Оберіть репліку на схемі'))+'</div>';var options=(data.nodes||[]).map(function(item){return'<option value="'+esc(item.id)+'"'+(item.id===data.entryId?' selected':'')+'>'+esc(item.id+' · '+local(item,'title'))+'</option>';}).join(''),targets=(data.nodes||[]).filter(function(item){return item.id!==node.id;});var links=(node.links||[]).map(function(link){return'<div class="zg-story-link-row"><select data-story-field="link-to" data-link-id="'+esc(link.id)+'">'+'<option value="">'+esc(t('Без реплики · только переход сцены','Без репліки · лише перехід сцени'))+'</option>'+targets.map(function(target){return'<option value="'+esc(target.id)+'"'+(target.id===link.to?' selected':'')+'>'+esc(local(target,'title'))+'</option>';}).join('')+'</select><input type="number" min="0" step="100" value="'+Math.max(0,Number(link.delayMs)||0)+'" data-story-field="link-delay" data-link-id="'+esc(link.id)+'" title="'+esc(t('Задержка, мс','Затримка, мс'))+'"><button type="button" data-story-remove-link="'+esc(link.id)+'" title="'+esc(t('Отсоединить линию, сохранив вариант ответа','Від’єднати лінію, зберігши варіант відповіді'))+'" aria-label="'+esc(t('Отсоединить линию','Від’єднати лінію'))+'">×</button><input style="grid-column:1/4" value="'+esc(local(link,'label'))+'" data-story-field="link-label" data-link-id="'+esc(link.id)+'" placeholder="'+esc(t('Название выбора или связи','Назва вибору або зв’язку'))+'"></div>';}).join('');return'<h3>'+esc(t('Реплика и переходы','Репліка та переходи'))+'</h3><p class="zg-story-note">'+esc(t('Номер реплики и линии виден на схеме — его можно назвать мне при следующей правке.','Номер репліки та лінії видно на схемі — його можна назвати мені під час наступної правки.'))+'</p><label class="zg-story-field"><span>'+esc(t('Начальная реплика','Початкова репліка'))+'</span><select data-story-field="entry">'+options+'</select></label><label class="zg-story-field"><span>ID</span><input value="'+esc(node.id)+'" readonly></label><label class="zg-story-field"><span>'+esc(t('Название','Назва'))+'</span><input data-story-field="title" value="'+esc(local(node,'title'))+'"></label><label class="zg-story-field"><span>'+esc(t('Кто говорит','Хто говорить'))+'</span><input data-story-field="speaker" value="'+esc(node.speaker||'')+'"></label><label class="zg-story-field"><span>'+esc(t('Текст реплики','Текст репліки'))+'</span><textarea data-story-field="text">'+esc(local(node,'text'))+'</textarea></label><h3>'+esc(t('Связи','Зв’язки'))+'</h3>'+links+'<button type="button" data-story-add-link'+' '+'>＋ '+esc(t('Добавить линию','Додати лінію'))+'</button> <button type="button" class="danger" data-story-remove-node'+((data.nodes||[]).length>1?'':' disabled')+'>'+esc(t('Удалить реплику','Видалити репліку'))+'</button>';}
  function render(){if(pointerPending){renderPending=true;return;}var data=project();if(w.ZargotaStoryBranch&&w.ZargotaStoryBranch.batch)return w.ZargotaStoryBranch.batch(data,function(){renderNow(data);});renderNow(data);}
  function renderNow(data){var root=ensureUi();if(!root.classList.contains('open'))return;var visible=w.ZargotaStoryLocationDialogues?w.ZargotaStoryLocationDialogues.nodes(data,data.activeSceneId||''):data.nodes;if(!visible.some(function(n){return n.id===selectedNodeId;}))selectedNodeId=visible[0]?.id||'';var projectSelect=root.querySelector('[data-story-project-select]');if(projectSelect)projectSelect.value=activeKey;if(!selectedNodeId||!nodeById(data,selectedNodeId))selectedNodeId=visible[0]?.id||'';root.querySelector('#zg-story-heading').textContent=t('Создание сюжета','Створення сюжету');root.querySelector('#zg-story-project').textContent=local(data,'title')+' · '+t('локально, вне игровой сессии','локально, поза ігровою сесією');root.querySelector('[data-story-add]').textContent='＋ '+t('Реплика','Репліка');root.querySelector('[data-story-scene]').textContent='🗺 '+t('Редактор сцены','Редактор сцени');root.querySelector('#zg-story-nodes').innerHTML=visible.map(function(node){var preview=local(node,'text').trim()||t('Текст пока не задан','Текст ще не заданий');return'<article class="zg-story-node'+(node.id===selectedNodeId?' selected':'')+'" data-node-id="'+esc(node.id)+'" style="left:'+Math.max(12,Number(node.x)||0)+'px;top:'+Math.max(12,Number(node.y)||0)+'px"><b>'+esc(local(node,'title')||node.id)+'</b><span>'+esc(preview.slice(0,90))+(preview.length>90?'…':'')+'</span><small>'+esc(node.id)+' · '+(node.links||[]).length+' '+esc(t('связ.','зв’яз.'))+'</small></article>';}).join('');drawLinks(Object.assign({},data,{nodes:visible}));root.querySelector('#zg-story-inspector').innerHTML=inspector(data,nodeById(data,selectedNodeId));enhanceInspector(data);renderSceneControls();}
  function reopenButton(){var button=document.getElementById('zg-story-reopen');if(button)return button;button=document.createElement('button');button.id='zg-story-reopen';button.className='zg-story-reopen';button.type='button';button.onclick=function(){w.zgStoryEditorOpen(activeKey);};document.body.appendChild(button);return button;}
  w.zgStoryEditorOpen=function(key){var previousKey=activeKey;activeKey=String(key||'workshop-story');var wasOpen=document.getElementById('zg-story-editor'),fresh=previousKey!==activeKey||!wasOpen||!document.getElementById('zg-game-overlay').classList.contains('story-mode');var root=ensureUi(),button=reopenButton();button.textContent='⌘ '+t('Диалоги','Діалоги');button.classList.remove('open');root.classList.add('open');applyChrome(true);render();if(fresh){var saved=project();if(saved.scene&&w.zgStorySceneLoad)w.zgStorySceneLoad(saved.scene);refreshStoryScenes(saved.scene?null:loadRememberedStoryScene);}else{captureScene();refreshStoryScenes();}return true;};
  w.zgStoryEditorClose=function(){if(w.ZargotaStoryActors)w.ZargotaStoryActors.close();if(w.ZargotaStoryStageEditor)w.ZargotaStoryStageEditor.close();var root=document.getElementById('zg-story-editor'),button=reopenButton();if(root)root.classList.remove('open');if(w.zgWorkshopMode==='story')button.classList.add('open');};
  w.zgStoryEditorDeactivate=function(){if(w.ZargotaStoryActors)w.ZargotaStoryActors.close();if(w.ZargotaStoryStageEditor)w.ZargotaStoryStageEditor.close();var root=document.getElementById('zg-story-editor'),button=document.getElementById('zg-story-reopen');if(root)root.classList.remove('open');if(button)button.classList.remove('open');applyChrome(false);if(w.ZargotaStoryPlayer)w.ZargotaStoryPlayer.stop();};
  w.zgStoryEditorProject=function(){return JSON.parse(JSON.stringify(project()));};
})(window);
