(function(w){
 'use strict';
 function t(a,b){return w.ZargotaI18n&&w.ZargotaI18n.getLocale()==='uk'?b:a;}
 function local(o,k){return t(o[k]||o[k+'Uk']||'',o[k+'Uk']||o[k]||'');}
 function create(data){return{active:data.initialQuestId||'',done:[]};}
 function enter(data,state,sceneId){if(!state||state.active)return null;var q=(data.quests||[]).find(function(q){return q.startSceneId===sceneId&&!(state.done||[]).includes(q.id)&&(!q.requiresQuestId||(state.done||[]).includes(q.requiresQuestId));});if(!q)return null;state.active=q.id;return q;}
 function complete(data,state,nodeId){var q=(data.quests||[]).find(function(q){return q.id===state.active;});if(!q||![q.dialogueId].concat(q.dialogueIds||[]).filter(Boolean).includes(nodeId)||state.done.includes(q.id))return null;state.done.push(q.id);state.active=q.nextId||'';return q;}
 function records(data){return(data.scenes&&data.scenes.length?data.scenes:[{id:data.activeSceneId||'',scene:data.scene,name:data.title}]).map(function(r){return Object.assign({},r,{scene:r.id===data.activeSceneId?data.scene:r.scene});});}
 function objects(scene){return ['tokens','zones','decorations'].flatMap(function(kind){return(kind==='tokens'?scene.tokens||[]:(scene.story||{})[kind]||[]).map(function(item){return{kind:kind,item:item};});});}
 function gatedScene(data,scene,sceneId,state){var copy=JSON.parse(JSON.stringify(scene));(data.quests||[]).forEach(function(q){if(state.done.includes(q.id))return;var reveals=w.ZargotaStoryQuestActions?w.ZargotaStoryQuestActions.list(q).filter(function(a){return a.type==='reveal'&&a.enabled!==false;}):q.reveal?[q.reveal]:[];reveals.forEach(function(a){if(a.sceneId!==sceneId)return;objects(copy).forEach(function(o){if(o.kind===a.kind&&o.item.id===a.id){o.item.visible=false;o.item.enabled=false;}});});});return w.ZargotaStoryQuestActions?w.ZargotaStoryQuestActions.apply(copy,sceneId,state):copy;}
 function edit(data,save,host){
  var opened=Array.from(host.querySelectorAll('details[open][data-quest-id]')).map(function(e){return e.dataset.questId;}),scroll=host.querySelector('.zg-quests-editor')?.scrollTop||0;host.replaceChildren();var panel=document.createElement('section');panel.className='zg-quests-editor';host.appendChild(panel);
  function element(tag,text,parent){var e=document.createElement(tag);if(text)e.textContent=text;(parent||panel).appendChild(e);return e;}
  function button(label,fn,parent){var b=element('button',label,parent);b.type='button';b.onclick=fn;return b;}
  function field(parent,label,value,fn,opts){var l=element('label',label,parent),i=element(opts?'select':'input','',l);i.setAttribute('aria-label',label);if(opts)opts.forEach(function(o){var e=element('option',o[1],i);e.value=o[0];});i.value=value||'';i.onchange=function(){fn(i.value);};return i;}
  function update(fn){save(fn);}
  function qset(id,key,value){update(function(d){var q=d.quests.find(function(q){return q.id===id;});q[key]=value;});}
  element('h2',t('Задания','Завдання'));
  element('p',t('Цель → завершение диалога → следующее задание → действия на карте.','Мета → завершення діалогу → наступне завдання → дії на карті.'));
  var quests=data.quests||[],options=[['',t('Нет','Немає')]].concat(quests.map(function(q){return[q.id,local(q,'title')||q.id];}));
  field(panel,t('Начальное задание','Початкове завдання'),data.initialQuestId,function(v){update(function(d){d.initialQuestId=v;});},options);
  if(!quests.length)element('p',t('Старая цель сохранена: ','Стару мету збережено: ')+local(data,'objective'));
  button(t('+ Задание','+ Завдання'),function(){update(function(d){d.quests=d.quests||[];var id='quest-'+Date.now().toString(36);d.quests.push({id:id,title:'Новое задание',titleUk:'Нове завдання',objective:'',objectiveUk:''});if(!d.initialQuestId)d.initialQuestId=id;});});
  quests.forEach(function(q){var card=element('details','');card.open=quests.length===1||opened.includes(q.id);card.dataset.questId=q.id;element('summary',(q.id===data.initialQuestId?'▶ ':'✧ ')+(local(q,'title')||q.id)+' · '+((q.actions||[]).length)+t(' действий',' дій'),card);element('h3',t('1. Цель для игрока','1. Мета для гравця'),card);var uk=w.ZargotaI18n&&w.ZargotaI18n.getLocale()==='uk';field(card,t('Название','Назва'),local(q,'title'),function(v){qset(q.id,uk?'titleUk':'title',v);});field(card,t('Что нужно сделать','Що потрібно зробити'),local(q,'objective'),function(v){qset(q.id,uk?'objectiveUk':'objective',v);});var translation=element('details','',card);element('summary',t('Перевод · украинский','Переклад · російська'),translation);field(translation,t('Название · UK','Назва · RU'),uk?q.title:q.titleUk,function(v){qset(q.id,uk?'title':'titleUk',v);});field(translation,t('Цель · UK','Мета · RU'),uk?q.objective:q.objectiveUk,function(v){qset(q.id,uk?'objective':'objectiveUk',v);});element('h3',t('2. Когда завершится','2. Коли завершиться'),card);
   var targets=[['',t('Выберите диалог','Оберіть діалог')]].concat((data.nodes||[]).map(function(n){return[n.id,(local(n,'title')||n.id)+' · '+local(n,'text').slice(0,65)+' ['+n.id+']'];}));
   field(card,t('Завершить диалог','Завершити діалог'),q.dialogueId,function(v){qset(q.id,'dialogueId',v);},targets);
   (q.dialogueIds||[]).forEach(function(id,index){var row=element('div','',card);field(row,t('Или завершить','Або завершити'),id,function(v){var ids=(q.dialogueIds||[]).slice();ids[index]=v;qset(q.id,'dialogueIds',ids);},targets);button(t('Убрать условие','Прибрати умову'),function(){qset(q.id,'dialogueIds',(q.dialogueIds||[]).filter(function(_,i){return i!==index;}));},row);});
   button(t('+ Другая концовка','+ Інша кінцівка'),function(){qset(q.id,'dialogueIds',(q.dialogueIds||[]).concat(['']));},card);
   var advanced=element('details','',card);element('summary',t('Дополнительно · ID и флаг','Додатково · ID і прапорець'),advanced);
   field(advanced,t('Или вставьте ID диалога','Або вставте ID діалогу'),q.dialogueId,function(v){qset(q.id,'dialogueId',v.trim());});
   if(q.dialogueId&&!(data.nodes||[]).some(function(n){return n.id===q.dialogueId;}))element('p',t('⚠ Диалог с таким ID не найден','⚠ Діалог із таким ID не знайдено'),card);
   field(card,t('Следующее задание','Наступне завдання'),q.nextId,function(v){qset(q.id,'nextId',v);},options.filter(function(o){return o[0]!==q.id;}));
   field(advanced,t('Сюжетный флаг после выполнения (необязательно)','Сюжетний прапорець після виконання (необов’язково)'),q.flag,function(v){qset(q.id,'flag',v);});
   element('h3',t('3. После выполнения · карта и звук','3. Після виконання · карта й звук'),card);
   if(w.ZargotaStoryQuestActionsEditor){w.ZargotaStoryQuestActionsEditor.edit(data,q,card,function(actions){qset(q.id,'actions',actions);});return;}var choices=[['',t('Без нового объекта','Без нового об’єкта')]],lookup={};records(data).forEach(function(r){objects(r.scene||{}).forEach(function(o){var key=JSON.stringify([r.id,o.kind,o.item.id]);lookup[key]={sceneId:r.id,kind:o.kind,id:o.item.id};choices.push([key,(r.name||r.id)+' · '+(local(o.item,'name')||o.item.id)+' · '+o.kind]);});});
   var value=q.reveal?JSON.stringify([q.reveal.sceneId,q.reveal.kind,q.reveal.id]):'';field(card,t('Появляется после выполнения','З’являється після виконання'),value,function(v){qset(q.id,'reveal',lookup[v]||null);},choices);
   element('small',t('Создайте и расположите любой объект во вкладке «Карта», затем выберите его здесь. До выполнения задания он скрыт только в игре.','Створіть і розташуйте будь-який об’єкт у вкладці «Карта», потім оберіть його тут. До виконання завдання він прихований лише у грі.'),card);
   if(q.reveal)button(t('Показать на карте','Показати на карті'),function(){var r=records(data).find(function(r){return r.id===q.reveal.sceneId;}),o=r&&objects(r.scene||{}).find(function(o){return o.kind===q.reveal.kind&&o.item.id===q.reveal.id;});if(!o)return;var dialog=document.createElement('dialog');dialog.className='zg-quest-map-preview';var map=document.createElement('div');map.style.cssText='position:relative;width:75vw;aspect-ratio:'+((r.scene.boardWidth||24)/(r.scene.boardHeight||16));var image=document.createElement('img');image.src=(r.scene.layers||[]).find(function(l){return l.visible!==false;})?.image||'';image.style.cssText='width:100%;height:100%;object-fit:fill';map.appendChild(image);var pin=document.createElement('span');pin.textContent='◎ '+(local(o.item,'name')||o.item.id);pin.style.cssText='position:absolute;color:#fff;background:#182a20;padding:8px;border:2px solid gold;transform:translate(-50%,-50%);left:'+o.item.x+'%;top:'+o.item.y+'%';map.appendChild(pin);dialog.appendChild(map);button(t('Закрыть','Закрити'),function(){dialog.remove();},dialog);document.body.appendChild(dialog);dialog.showModal();},card);
  });panel.scrollTop=scroll;
 }
 w.ZargotaStoryQuests={create:create,enter:enter,complete:complete,gatedScene:gatedScene,edit:edit};
})(window);
