const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const workspace = fs.readFileSync(path.join(root, 'arena-v2-workspace.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'arena-v2-workspace.css'), 'utf8');

assert(html.includes('arena-v2-workspace.css?v=2026-09-01.34'), 'Arena workspace stylesheet must be loaded');
assert(html.includes('arena-v2-workspace.js?v=2026-09-01.28'), 'Arena workspace controller must be loaded');
assert(html.includes("global.zgArenaWorkspaceOpen==='function'"), 'Arena tab must open the battlefield workspace directly');
assert(html.includes('w.zgArenaV2Launch=function(config)'), 'VTT must expose the local Arena launch adapter');
assert(html.includes('w.zgArenaV2AddParticipant=function(participant,position)'), 'Arena must add participants directly to the live field');
assert(html.includes('w.zgArenaV2GetState=function()'), 'Arena must export its current state for full battle presets');
assert(html.includes('w.zgArenaV2OpenTokenBag=function(tokenId,panel)'), 'Arena creature tokens must open the existing bag');
assert(html.includes("w.zgLocalArenaV2Active&&(!drawer||!drawer.classList.contains('open'))"), 'Clicking an Arena creature must open its bag even when the drawer was closed');
assert(html.includes("member.role==='scene-token'&&member.sceneTokenId&&w.zgLocalArenaV2Active"), 'Arena creature inventory must be editable only in the local Arena copy');
assert(html.includes("getData('text/zargota-arena-item')"), 'Existing bag must accept Arena catalog drops');
assert(html.includes('w.zgVttInventoryCatalogAdd=function(catalogId)'), 'Catalog plus button and drop must share one bag-add path');
assert(html.includes('w.zgVttInventoryCatalogEquip=function(catalogId,slotName)') && html.includes("getData('text/zargota-arena-item')"), 'Arena catalog equipment must drop directly into compatible bag slots');
assert(html.includes('function inventoryWeaponProjection(character,baseProfiles)') && html.includes('function applyInventoryCombatProjection(target,character,baseProfiles)'), 'Arena inventory mutations must rebuild the equipped weapon projection');
assert(html.includes('applyInventoryCombatProjection(token,projected,token.weaponProfiles)') && html.includes('applyInventoryCombatProjection(entry,projected,entry.weaponProfiles)') && html.includes('applyInventoryCombatProjection(heroToken,projected,heroToken.weaponProfiles)') && html.includes('applyInventoryCombatProjection(heroEntry,projected,heroEntry.weaponProfiles)'), 'Arena equipment must synchronize weapons to creature and hero tokens plus combat entries');
assert(html.includes("source=Object.assign({},attacker,character,{inventoryItems:character.inventoryItems||attacker.inventoryItems") && html.includes("inventoryWeaponProjection(source,attacker.weaponProfiles)"), 'Attack selection must recover equipped weapons from the current Arena bag when the combat snapshot is stale');
assert(html.includes('function inventoryClone(value,fallback)') && html.includes('item=inventoryClone(source,{})'), 'Bag catalog path must clone inside the drawer module scope');
assert(html.includes('item.equipped=false'), 'Catalog drops must enter the bag unequipped');
assert(html.includes("member.role==='scene-token'&&member.sceneTokenId&&w.zgLocalArenaV2Active") && html.includes("detail:{kind:'magic',tokenId:arenaTokenId}"), 'Arena token spell editing must update the local scene copy and combat entry');
assert(html.includes("pendingAbilityCast.masterActorKey=arenaCaster?String(arenaEntry&&arenaEntry.key") && html.includes("String(arenaTurn.tokenId||'')===String(pending.casterTokenId||'')") && html.includes('arenaVttAbilityTargetKeys(payload,selection,arenaCasterKey)') && html.includes("payload.playbackMode='instant'") && html.includes("updatedBy:'arena-master'"), 'Arena token spells must cast from the bag and consume the local copy resource');
assert(html.includes('profile.resourceMax=Math.max(0,Number(selectedProfile.resourceMax)||Number(selectedCard.limit)||0)') && html.includes('profile.resourceUsed=Math.max(0,Number(selectedProfile.resourceUsed)||Number(selectedCard.used)||0)'), 'Arena casts must preserve the visible spell card charge state in the battle profile');
assert(html.includes("cooldownMatch=String(source&&source.cd||'').match") && html.includes('profile.resourceMax=Math.max(0,Number(profile.resourceMax)||canonicalLimit'), 'Arena spell requests must recover their canonical charge limit even without a live card model');
assert(html.includes('resolvedResourceKey=String(payload.resourceKey||resolvedCard.key||pending.key') && html.includes('holder.spellCD[resolvedSpellId]') && html.includes("[resolvedActor,resolvedToken].forEach") && html.includes('scopeKey:resolvedScopeKey') && html.includes('battleUsed:Math.max(resolvedBattleUsed') && html.includes("w.zgArenaV2SyncSnapshot(snapshot)") && html.includes("w.zgVttApplyTestSnapshot(snapshot)"), 'Arena cast result must synchronize scoped charges to both the combat entry, scene token, and visible bag state');
assert(html.includes('w.zgArenaV2GetActorPatch=function(tokenId)') && html.includes("arenaPatch=w.zgLocalArenaV2Active") && html.includes('spellCD:arenaPatch.spellCD'), 'Arena bag must read the latest local spell charge patch after a cast');
assert(html.includes("Заклинание можно применить только в ход этого участника") && html.includes("masterControlled&&!w.zgLocalArenaV2Active"), 'Arena bag must guard the visible current turn while the online resolver keeps its own turn check');
assert(html.includes('function syncTokenEffectSize(node)') && html.includes("node.style.setProperty('--zg-token-size'"), 'Defeated token playback must size its local visual effects without throwing');
assert(html.includes("sourceSnapshot=sourceSnapshot&&sourceSnapshot.room?sourceSnapshot:roomSnapshot") && html.includes('var activeSnapshot=arenaV2SyncedSnapshot') && html.includes('arenaV2SyncedSnapshot=null;arenaV2ActorPatches={}') && html.includes("w.zgArenaV2SyncSnapshot=function(snapshot)"), 'Arena presets and combat actions must use the latest synchronized Arena snapshot and clear stale cache on launch');
assert(html.includes('abilityUsage:raw.abilityUsage||{}') && html.includes('spellCD:raw.spellCD||{}') && html.includes('spellCD:primarySource.spellCD||{}') && html.includes('spellCD:token.spellCD||{}'), 'Arena presets must preserve local spell and skill charges');
assert(html.includes("['character','npc','beast','spell-summon','construct']") && html.includes('spellRefs: Array.isArray(token.spellRefs)') && html.includes('equipItems: Array.isArray(token.equipItems)'), 'Scene token normalization must preserve Arena character links, magic, and equipment');
assert(html.includes("roomState(snapshot);if(typeof w.zgArenaV2SyncSnapshot==='function')w.zgArenaV2SyncSnapshot(snapshot);applyScene()"), 'Arena launch and participant placement must immediately synchronize the complete local snapshot');
assert(html.includes("w.zgArenaV2ApplyActorPatch=function(tokenId,patch)") && html.includes("arenaV2ActorPatches[String(token.id||'')]") && html.includes("w.zgArenaV2ApplyActorPatch(arenaTokenId,{spellRefs:"), 'Arena presets must merge local token magic patches into the saved actor copy');
assert(html.includes("document.body.classList.remove('zg-arena-v2')"), 'Leaving Arena must clean up its presentation mode');

['Создать героя','Створити героя','Противники','Предметы','Предмети','Каталог','Пресеты боя','Пресети бою'].forEach((copy) => {
  assert(workspace.includes(copy), `Arena workspace must include bilingual copy: ${copy}`);
});
assert(workspace.includes("navButton('hero'") && workspace.includes("navButton('opponents'") && workspace.includes("navButton('items'") && workspace.includes("navButton('spells'") && workspace.includes("navButton('presets'"), 'Left rail must expose the five requested sections');
assert(workspace.includes("state.opponentTab==='bestiary'") && workspace.includes("state.opponentTab==='custom'"), 'Opponent drawer must offer Bestiary and custom creation');
assert(workspace.includes("text('Пресет: гуманоид второго уровня."), 'Custom opponent must include the level-two humanoid preset');
assert(workspace.includes('BEAST_PAGE_SIZE=10') && workspace.includes('data-arena-beast-filter') && workspace.includes('data-arena-beast-reset'), 'Arena Bestiary must paginate and expose the reusable filter set');
assert(workspace.includes("global.ZargotaProgression.builderProjection") && workspace.includes('data-arena-builder-race') && workspace.includes('data-arena-stat'), 'Temporary hero builder must reuse progression race, level, and stat projection');
assert(workspace.includes('data-arena-stat-scope') && workspace.includes("customSelect('enemy-level'") && workspace.includes('data-arena-enemy-vital'), 'Custom opponent must reuse styled race, level, stat, and vital controls');
assert(workspace.includes('enemyVitalAdjustments:{hp:0,ac:0,initiative:0}') && workspace.includes('function enemyVitalModel(name)') && workspace.includes("builderProjection('enemy')"), 'Opponent vitals must scale from canonical progression while preserving manual adjustments');
assert(workspace.includes('Автоматический расчёт по Мануалу') && workspace.includes('Автоматичний розрахунок за Мануалом') && workspace.includes("text('База масштабируется автоматически"), 'Manual scaling must be visibly explained in both locales');
assert(workspace.includes('scrollTop=preserve&&body?body.scrollTop:0') && workspace.includes('current.scrollTop=scrollTop') && workspace.includes('refresh({preserveScroll:false})'), 'Inline opponent adjustments must preserve drawer scroll while panel switches reset it');
assert(workspace.includes('Number(enemy?state.enemyLevel:state.builderLevel)') && workspace.includes('String(enemy?state.enemyRace:state.builderRace)'), 'Arena builders must submit their live state instead of translation-stripped hidden values');
assert(workspace.includes("images/vtt-icons/health.png") && workspace.includes("images/ui/stats/armor.png") && workspace.includes("images/ui/stats/initiative.png"), 'Opponent vitals must use project icon assets');
assert(workspace.includes('function spellBookIcon') && workspace.includes("kodex:'codex',folio:'folio',obrad:'ritual'"), 'Arena spell cards must reuse book-type artwork');
assert(workspace.includes('entry.removable?\'<button') && workspace.includes('data-arena-hero-delete') && workspace.includes('function protectedCampaignHero(source)'), 'Arena-only and non-campaign local heroes must expose removal while campaign heroes stay protected');
assert(workspace.includes('HIDDEN_HERO_KEY') && workspace.includes('state.hiddenHeroIds.push(entry.sourceId)') && workspace.includes('Данные в разделе «Персонажи» останутся'), 'Removing a local hero from Arena must hide it without deleting character data');
assert(workspace.includes('class="zg-arena-item" draggable="true" tabindex="0" data-arena-item'), 'Item catalog cards must be draggable and keyboard focusable');
assert(workspace.includes('data-arena-item-add'), 'Item catalog cards must also expose a direct add button');
assert(workspace.includes("global.zgVttInventoryCatalogAdd(button.dataset.arenaItemAdd)"), 'Direct add button must use the existing bag catalog path');
assert(workspace.includes("event.dataTransfer.setData('text/zargota-arena-item',id)"), 'Item dragging must use the Arena-to-bag MIME contract');
assert(workspace.includes('setTimeout(function(){itemHoverTimer=0;showItemPreview') && workspace.includes('},300)') && workspace.includes("role','tooltip"), 'Hovering an Arena item for 300 milliseconds must open its full preview card');
assert(workspace.includes("text('Урон','Шкода')") && workspace.includes("text('Свойства','Властивості')") && workspace.includes("text('Описание','Опис')") && workspace.includes("text('Цена','Ціна')"), 'Arena item preview must expose bilingual stats, properties, description, and price');
assert(workspace.includes("left=(drawerRect?drawerRect.right:anchorRect.right)+12") && workspace.includes('global.innerWidth-width-12'), 'Arena item preview must prefer the right side and stay inside the viewport');
assert(workspace.includes("event.dataTransfer.setData('text/zargota-arena-spell',id)") && workspace.includes("event.dataTransfer.setData('application/x-zargota-arena-spell-'+type,id)") && workspace.includes('implementedSpellIds') && workspace.includes('Не полностью внедрено'), 'Spell catalog must support typed drag/click and implementation markers');
assert(workspace.includes('spellReadyFirst:true') && workspace.includes('data-arena-ready-first') && workspace.includes("Number(!!implemented[String(b.spell.id)])"), 'Spell catalog must default to implemented spells first and expose a visible toggle');
assert(workspace.includes('function customSelect(group,current,options,extraClass)') && workspace.includes('data-arena-select-option'), 'Arena filters and race builders must use the styled select control');
assert(workspace.includes('race-portraits-atlas-v1.png') || css.includes('race-portraits-atlas-v1.png'), 'Arena race controls must reuse the generated portrait atlas');
assert(workspace.includes("arenaRacePortrait:RACE_ART[race]||'human'"), 'Arena-created actors must preserve their selected race portrait');
assert(html.includes('arenaRacePortrait:arenaRacePortraitKey(token.arenaRacePortrait)') && html.includes('zg-vtt-token-ph zg-race-portrait'), 'Arena token copies must render the preserved race portrait on the battlefield');
assert(html.includes('racePortrait=arenaRacePortraitKey(entry.arenaRacePortrait)') && html.includes('zg-party-ph zg-race-portrait') && html.includes('<i class="zg-race-portrait race-'), 'Arena combat cards must repeat the preserved race portrait in the upper party and initiative surfaces');
assert(html.includes('w.zgArenaV2GrantSpell=function(tokenId,spellId,prepareType)') && html.includes('w.zgVttArenaSpellCatalogDrop=function(event,prepareType)') && html.includes("prepareType?'spell-prepare':'spell'"), 'Spell catalog drops must either grant or grant-and-prepare on the selected Arena copy');
assert(html.includes('w.zgArenaV2AdjustActorHp=function(tokenId,delta)') && html.includes('w.zgArenaV2SetActorStatus=function(tokenId,statusKey,enabled)'), 'Arena right click controls must expose local HP and status mutations');
assert(html.includes("w.zgLocalArenaV2Active&&typeof w.zgArenaWorkspaceOpenQuickMenu==='function'"), 'Arena token context menu must bypass the full GM console');
assert(html.includes("title.textContent=uk?'Покинути арену?':'Покинуть арену?'") && html.includes("button.textContent=uk?'Покинути арену':'Покинуть арену'"), 'Arena exit dialog must use Arena-specific bilingual copy');
assert(!workspace.includes('loadArmorySets') && !workspace.includes('Комплект снаряжения') && !workspace.includes('Комплект спорядження'), 'Arena drawers must not implement a second equipment/loadout form');
assert(workspace.includes('actors:clone(current.actors,[])'), 'Battle presets must store the full current actor copies');
assert(workspace.includes('while(occupied[key]&&step<8)') && workspace.includes("key=Math.round(x*10)+'|'+Math.round(y*10)"), 'Preset loading must separate participants that occupy the same position');
assert(css.includes('.zg-arena-drawer[data-panel="items"]') && css.includes('--arena-drawer-width:510px'), 'Items drawer must be wider than compact drawers');
assert(css.includes('--arena-rail:146px') && css.includes("font:700 9.4px/1.15 'Cinzel'"), 'Arena rail and labels must be approximately thirty percent larger');
assert(css.includes('#zg-game-overlay.arena-v2-mode .zg-vtt-drawer{z-index:23}'), 'Existing right bag must stay above Arena drawers');
assert(css.includes('.arena-workspace-panel-open .zg-arena-workspace{z-index:70}') && css.includes('inset:8px auto 18px 12px'), 'Open Arena panels must start at the top and layer above combat tools');
assert(css.includes('.zg-arena-scaling-note') && css.includes('.zg-arena-vital span em.adjusted'), 'Manual scaling and base adjustments must have a clear Arena visual treatment');
assert(css.includes('Arena readability v2') && css.includes('.zg-arena-stat span b{font-size:13px}') && css.includes('.zg-arena-select summary{font-size:16.9px}'), 'Arena workspace typography must be enlarged by approximately thirty percent without whole-panel zoom');
assert(css.includes('.zg-arena-filters{margin:-6px -4px 4px;padding:6px 4px 8px') && css.includes('.zg-arena-filters button:hover'), 'Arena item filter hover must have enough padded space to avoid clipping');
assert(css.includes('.zg-arena-item-preview{position:fixed') && css.includes('@keyframes zgArenaItemPreviewIn'), 'Arena item preview must use a themed non-blocking floating card');
assert(css.includes('.zg-arena-item img{mix-blend-mode:screen') && css.includes('isolation:isolate'), 'Arena item art must blend away baked square backgrounds without clipping the object');
assert(css.includes('Arena combat dock: 120% geometry and 130% labels') && css.includes('width:min(998px,calc(100vw - 250px));height:152px') && css.includes('.zg-combat-economy button>b{min-height:31px;font-size:13px') && css.includes('.zg-combat-economy button>small{min-height:28px;font-size:11.7px'), 'Arena combat dock must preserve enlarged labels without clipping two-line copy');
assert(css.includes('--bag-layout-shift:.2') && css.includes('--bag-rest-transform:translate(20%,-50%)') && css.includes('--bag-entry-transform:translate(20%,-50%)') && css.includes('right:0'), 'Desktop Arena bag must rest farther to the right without an opening jump');
assert(css.includes('transform-origin:right center'), 'Desktop Arena bag must scale from its vertical center');
assert(html.includes("drawer.getAttribute('data-player-bag-scale')==='large'||w.zgLocalArenaV2Active") && html.includes('arenaAvoidBag?{avoidOverlap:true,leftInset:12,gap:14}:null') && html.includes('var drawerLeft=options&&options.avoidOverlap?drawerRect.left:Math.min') && html.includes('var alignedLeft=Math.max(safeLeft,drawerLeft-gap-hostRect.left-targetWidth)'), 'Arena combat tools must align beside the visible edge of every open bag size without overlap');
assert(css.includes('#zg-game-overlay.arena-v2-mode #zg-combat-economy.bag-docked') && css.includes('width:var(--zg-player-dock-width)') && css.includes('overflow-x:auto') && css.includes('bag-docked button{min-width:88px'), 'Arena dock must honor the collision-safe width and scroll instead of entering the bag on narrow screens');
assert(css.includes('.zg-vtt-drawer.open.backpack-skin{z-index:65}') && css.includes('.zg-combat-own-turn{z-index:22}'), 'Open Arena bag must layer above the current-turn circle');
assert(css.includes('.zg-player-dock{z-index:8;transition:none!important}'), 'Arena bag and bottom dock must not jump during opening');
assert(css.includes('#zg-game-overlay.arena-v2-mode #zg-world-clock') && css.includes('#zg-game-overlay.arena-v2-mode #zg-vtt-journal'), 'Arena must hide time and session chat');
assert(html.includes("notesUk: 'Локальну Арену повністю переперевірено"), 'Arena changelog must include Ukrainian copy');
assert(html.includes("v: '2026-09-01.26'") && html.includes("notesUk: 'Усю типографіку локальної Арени"), 'Arena readability release note must remain bilingual');
assert(html.includes("v: '2026-09-01.28'") && html.includes("notesUk: 'У каталозі предметів Арени виправлено обрізання"), 'Arena hover preview release note must be bilingual');
assert(html.includes("v: '2026-09-01.29'") && html.includes("notesUk: 'Відкриту сумку в локальній Арені посунуто праворуч"), 'Arena bag collision release note must be bilingual');
assert(html.includes("v: '2026-09-01.31'") && html.includes("notesUk: 'У каталозі предметів Арени прибрано помітну квадратну підкладку"), 'Arena item artwork blending release note must be bilingual');
assert(html.includes("v: '2026-09-01.32'") && html.includes("notesUk: 'У локальній Арені відкриту сумку посунуто ще праворуч"), 'Arena bag and dock alignment release note must be bilingual');
assert(html.includes("v: '2026-09-01.34'") && html.includes("notesUk: 'Закляття з каталогу Арени тепер можна перетягувати"), 'Arena spell drag destinations release note must be bilingual');
assert(html.includes("v: '2026-09-01.35'") && html.includes("notesUk: 'Виправлено спорядження зброї в локальній Арені"), 'Arena equipped weapon synchronization release note must be bilingual');

const progression = fs.readFileSync(path.join(root, 'zargota-progression.js'), 'utf8');
assert(progression.includes('zoom:1.35') && progression.includes('calc(100% / 1.35)'), 'Progression planner must be visually enlarged by 35 percent without overflowing the viewport');
assert(progression.includes('function racePickerHtml()') && progression.includes('race-portraits-atlas-v1.png'), 'Progression builder must use a styled race picker with race artwork');
assert(progression.includes("global.zgStatIcon === 'function'") && progression.includes('.zgp-builder-stat .zg-stat-icon'), 'Progression builder must use and enlarge the existing stat icons');

console.log('arena-v2.test.js: OK');
