'use strict';

var assert = require('assert');
var fs = require('fs');
var path = require('path');

var root = path.resolve(__dirname, '..');
var html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
var network = fs.readFileSync(path.join(root, 'zargota-network.js'), 'utf8');
var todo = fs.readFileSync(path.join(root, 'COMBAT_REACTIONS_TODO.md'), 'utf8');

assert.match(network, /function normalizePreparedReactionInput\(/);
assert.match(network, /version:2,text:text,triggerKind:triggerKind/);
assert.match(network, /prepareCombatReaction: function \(intent, participantKey\)/);
assert.match(network, /return api\.requestAction\(text, 'combat-prepare', '', preparedIntent\)/);
assert.match(network, /request\.actionKind === 'combat-prepare'/);
assert.match(network, /resolutionOperationId:'combat-prepare-' \+ currentRequest\.id/);
assert.match(network, /entry\.preparedReaction=Object\.assign\(\{\},preparedIntent/);
assert.match(network, /preparedReaction:prepared/);
assert.match(network, /cancelPreparedReaction: function/);
assert.match(network, /resolvePendingPreparedItem: function/);
assert.match(network, /requestCombatReaction: function/);
assert.match(network, /useMasterCombatReaction: function/);
assert.match(network, /answerCombatReaction: function/);
assert.match(network, /finishPendingReaction: function/);
assert.match(network, /store\.applyInventoryOperations\(character,\[operation\]/);
assert.match(network, /appliedPreparedOperationIds/);
assert.match(network, /configurePendingCombatDamage: function/);
assert.match(network, /var critical=!!pendingDamage\.critical/);
assert.match(network, /kept===1\?1:kept\+Number\(row\.entry\.bonus\|\|0\)/);
assert.match(html, /id="zg-combat-prepare-trigger"/);
assert.match(html, /id="zg-combat-prepare-action"/);
assert.match(html, /id="zg-combat-prepare-target"/);
assert.match(html, /id="zg-combat-prepare-weapon"/);
assert.match(html, /id="zg-combat-prepare-item"/);
assert.match(html, /intent\.actionKind==='use-item'&&!intent\.itemId/);
assert.match(html, /Подтвердить подготовку/);
assert.match(html, /Заявка на подготовку отправлена мастеру/);
assert.match(html, /zgCombatPreparedCancel/);
assert.match(html, /id="zg-combat-prepared-item"/);
assert.match(html, /prepareReady=!!\(canAct&&isTurn&&Number\(economy\.long\)>0/);
assert.match(html, /Длительное действие уже потрачено\. Оно восстановится в начале следующего хода\./);
assert.match(html, /Готово · ждёт условия/);
assert.match(html, /\.zg-prepared-ready\{/);
assert.match(html, /id="zg-combat-reaction-prompt"/);
assert.match(html, /id="zg-combat-reaction-actor"/);
assert.match(html, /Использовать реакцию существа/);
assert.match(html, /zgCombatPreparedItemResolve\(true\)/);
assert.match(html, /Применить без расхода/);
assert.match(html, /Применить и списать 1/);
assert.match(html, /Сработало · ждёт решения/);
assert.match(html, /zgCombatPreparedPendingResume/);
assert.match(html, /zgCombatAttackBeginTargeting\(\)/);
assert.match(html, /Реакция — только когда мастер нажмёт «Исполнить»/);
assert.match(todo, /Подготовленное действие/);
assert.match(todo, /Обычная реакция/);
assert.match(todo, /Отложенное событие/);
assert.match(todo, /не списывает предмет автоматически/);

console.log('combat reaction intent contract passed');
