'use strict';

var assert = require('assert');
var fs = require('fs');
var path = require('path');

var root = path.resolve(__dirname, '..');
var html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
var network = fs.readFileSync(path.join(root, 'zargota-network.js'), 'utf8');

assert.match(html, /id="zg-combat-intent"/);
assert.match(html, /zgCombatIntentSubmit/);
assert.match(html, /zgCombatIntentKind/);
assert.match(html, /zg-combat-intent-kinds/);
assert.match(html, /Отправить заявку Мастеру/);
assert.match(html, /zgCombatIntentResolveOpen/);
assert.match(html, /zgCombatIntentDragStart/);
assert.match(html, /Назначить бросок/);
assert.match(html, /Оповестить игрока/);
assert.match(html, />Провал<\/button><button[^>]*>Успех<\/button>/);
assert.match(html, /combatRequestAction\(intentApi,text,'combat-intent'/);
assert.match(html, /Без броска/);
assert.match(html, /Решение ГМа · без автоэффекта/);
assert.match(network, /actionKind === 'combat-intent'/);
assert.match(network, /configureCombatIntent: function/);
assert.match(network, /rollCombatIntent: function/);
assert.match(network, /finishCombatIntent: function/);
assert.match(network, /actionCost:'short'/);
assert.match(network, /resolutionOperationId:'combat-intent-' \+ currentRequest\.id/);
assert.match(network, /economy\.short = Math\.max\(0, Number\(economy\.short \|\| 0\) - 1\)/);
assert.match(network, /manualResolution:true/);
assert.match(network, /status:'roll-requested', stage:'waiting-roll'/);
assert.match(network, /status:'roll-result',stage:'roll-result'/);
assert.match(html, /renderCombatIntent\(false\)/, 'room snapshots must not rebuild the open intent form while the player is editing it');
assert.match(html, /Заявка на короткое действие отправлена/, 'the player must receive explicit submission feedback');
assert.match(network, /accepted && request\.status !== 'roll-result'/, 'GM cannot accept a check before the player actually rolls');
assert.match(html, /<textarea id="zg-action-custom" maxlength="1000"/, 'custom actions must allow a long multiline description');
assert.match(html, /oninput="zgVttActionCustomResize\(this\)"/, 'the custom action field must grow with its text');
assert.match(html, /custom:'images\/vtt-actions\/cursors\/custom\.png'/, 'custom targeting must use the dedicated cursor artwork');
assert.match(html, /class="zg-action-cursor-glyph"/, 'custom targeting uses the approved full-size cursor glyph');
assert.match(html, /cursorIcon\+'\?v=20260820\.2" alt="" aria-hidden="true"/, 'cursor artwork must use the current cache key');
assert.match(html, /\.zg-action-cursor\{[^}]*overflow:visible;[^}]*contain:layout style/, 'the one-pixel cursor anchor must not clip its artwork in Safari');
assert.doesNotMatch(html, /\.zg-action-cursor\{[^}]*contain:layout paint/, 'paint containment must not hide action cursors outside their one-pixel anchor');
assert.doesNotMatch(html, /class="zg-action-cursor-label"/, 'approved glyphs replace the unreadably small duplicate cursor labels');
assert.doesNotMatch(html, /if\(kind==='movement'\)return '';/, 'movement uses the approved footprint glyph like every other action');
assert.match(html, /movement:'images\/vtt-actions\/cursors\/movement\.png'/, 'movement keeps its dedicated footprint cursor asset');
['Осмотреть','Взаимодействовать','Искать','Говорить','Взять','Атаковать','Другое действие'].forEach(function(label){
  assert.match(html, new RegExp("[\\'\"]"+label+"[\\'\"]"), label+' must have a cursor label');
});
assert.match(html, /w\.zgActionRequestDetailsOpen=function\(uid,request\)/, 'the GM must be able to open a wide custom-request view from a bound request snapshot');
assert.match(html, /zgActionRequestCheckOpen/, 'custom request cards must expose the existing characteristic-check flow');
assert.match(html, /function combatIntentResolveRequest\(uid\)/, 'the GM check dialog must resolve its request through one shared snapshot helper');
assert.match(html, /requestFrom\(roomSnapshot\),requestFrom\(state\)/, 'the GM check dialog must prefer the live room snapshot and retain the combat-state fallback');
assert.match(html, /w\.zgActionRequestCheckOpen=function\(uid,request\)\{request=request&&typeof request==='object'\?request:currentActionRequestForMember\(uid\)/, 'the bound request is preferred before the live-state fallback');
assert.match(html, /w\.zgCombatIntentResolveOpen=function\(uid,request\)/, 'the check dialog receives the captured request directly');
assert.match(html, /data-action-request-command="check"/, 'the check button uses an explicit request command instead of a fragile inline lookup');
assert.match(html, /data-action-request-command="open"/, 'the full-request button uses an explicit request command instead of a fragile inline lookup');
assert.match(html, /button\.addEventListener\('click',function\(ev\)\{ev\.preventDefault\(\);ev\.stopPropagation\(\);var command=button\.getAttribute\('data-action-request-command'\)/, 'request commands are wired directly when the card is rendered');
assert.match(html, /zgActionRequestCheckOpen\(request\.uid,request\)/, 'the check command passes the exact rendered request snapshot');
assert.match(html, /zgActionRequestDetailsOpen\(request\.uid,request\)/, 'the full-request command passes the exact rendered request snapshot');
assert.match(html, /combatIntentResolveRequestSnapshot/, 'the check dialog retains its request while opening');
assert.match(html, /request=combatIntentResolveRequest\(combatIntentResolveUid\)/, 'the GM check dialog renderer must not read only the potentially stale combat state');
assert.match(html, /Заявка уже закрыта или ещё не успела синхронизироваться/, 'the GM check dialog must never leave an unexplained empty shell');
assert.match(html, /function manualCheckActionKind\(kind\)/, 'all manual scene actions must share one characteristic-check contract');
assert.match(html, /manualCheckActionKind\(request\.actionKind\)/, 'the shared player roll UI must accept every manual scene action');
assert.match(network, /trim\(\)\.slice\(0, 1200\)/, 'the network request must preserve the expanded custom description');
assert.match(network, /function isManualCheckActionKind\(kind\)/, 'the network transaction must recognize every manual scene action');
assert.match(network, /manualActionRequest=!!\(request&&isManualCheckActionKind\(request\.actionKind\)\)/, 'the GM check transaction must use the shared manual-action contract');
assert.match(network, /else mode='check'/, 'custom requests must remain a simple characteristic check against DC');

console.log('combat intent request contract passed');
