'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');

const html = fs.readFileSync(path.resolve(__dirname, '..', 'index.html'), 'utf8');

assert.strictEqual((html.match(/id="zg-irl-character-dock"/g) || []).length, 1, 'IRL table needs exactly one five-hero dock');
assert.strictEqual((html.match(/id="zg-irl-character-card"/g) || []).length, 1, 'IRL table needs exactly one expanded character card');
assert.match(html, /var IRL_HERO_ORDER=\['lin-yin','vrotik','evan','melissa','esteros'\]/, 'the established five-player order must remain stable');
assert.match(html, /function irlHeroList\(\)[\s\S]*?Array\.isArray\(w\.characters\)/, 'cards must read the shared character registry');
assert.match(html, /typeof w\.zgStatIcon==='function'\?w\.zgStatIcon\(key,'zg-irl-stat-icon'\)/, 'the dock card must reuse the shared stat icon assets');
assert.match(html, /function irlStatuses\(character\)[\s\S]*?character&&character\.statuses[\s\S]*?character&&character\.statusEffects/, 'states must come from the character sheet data');
assert.match(html, /function irlAbilities\(character,consoleState,heroKey\)[\s\S]*?character&&character\.skills[\s\S]*?character&&character\.mastery/, 'abilities must come from the character sheet data');
assert.match(html, /function irlAbilities\(character,consoleState,heroKey\)[\s\S]*?character&&character\.spellRefs[\s\S]*?irlSpellById/, 'linked grimoire spells must be included beside sheet abilities');
assert.match(html, /function irlSpellById\(id\)[\s\S]*?findCharacterCatalogSpell/, 'spell references must resolve through the shared character spell catalog');
assert.match(html, /function irlAbilities\(character,consoleState,heroKey\)[\s\S]*?description:irlLongText\(raw\.description/, 'ability cards must retain the full sheet description');
assert.doesNotMatch(html.match(/function irlAbilities\(character,consoleState,heroKey\)[\s\S]*?\n  \}/)[0], /\.slice\(0,4\)/, 'the IRL card must not silently hide later abilities');
assert.match(html, /w\.zgIrlCharacterToggle=function\(key\)[\s\S]*?state\.selectedKey===key\?'':key/, 'portrait click must explicitly open and close the selected card');
assert.match(html, /w\.zgIrlCharacterEntryToggle=function\(kind,index\)[\s\S]*?if\(kind!=='ability'\)return[\s\S]*?state\.expandedEntry===entryKey\?'':entryKey/, 'ability rows must explicitly expand and collapse on click');
assert.match(html, /class="zg-irl-entry-toggle"[\s\S]*?aria-expanded=/, 'expandable rows must be real accessible buttons');
assert.match(html, /function irlAbilityVisual\(raw,sourceKind\)[\s\S]*?kind='spell'[\s\S]*?kind='passive'[\s\S]*?kind='trait'[\s\S]*?kind='short'[\s\S]*?kind='long'/, 'ability cards must distinguish spells, passive traits, styles, short and long actions');
assert.match(html, /function irlAbilityDisplayName\(value\)[\s\S]*?quoted=name\.match[\s\S]*?позиция\|черта\|риса\|стиль/, 'large card titles must remove repeated action prefixes while preserving authored names');
assert.match(html, /\{obrad:'ritual',folio:'folio',kodex:'codex'\}/, 'spell cards must reuse the established session spell art');
assert.match(html, /function irlSpellSections\(spell\)[\s\S]*?Проявление[\s\S]*?Эффект и механика[\s\S]*?Активация · изучение[\s\S]*?Ограничения/, 'expanded spells must preserve the important authored sections');
assert.match(html, /function irlRuleTone\(line\)[\s\S]*?return'critical'[\s\S]*?return'success'[\s\S]*?return'failure'[\s\S]*?return'healing'[\s\S]*?return'damage'[\s\S]*?return'check'[\s\S]*?return'restriction'[\s\S]*?return'roleplay'/, 'mechanical lines must receive distinct semantic color tones');
assert.match(html, /function irlRuleLinesHtml\(text\)[\s\S]*?esc\(line\)/, 'highlighted rules must escape authored text before adding markup');
assert.match(html, /ability-card kind-'\+esc\(visual\.kind[\s\S]*?tone-'\+esc\(visual\.tone/, 'each ability card must carry both action-type and character-flavor themes');
assert.match(html, /function irlStatusRules\(effect,mechanics\)[\s\S]*?cantAct[\s\S]*?startOfTurnEffect/, 'expanded statuses must expose mechanics from the shared status catalog');
assert.match(html, /if\(!isAbility\)return'<article class="'\+articleClass\+'"><div class="zg-irl-entry-toggle">'[\s\S]*?class="zg-irl-entry-detail">'\+detailHtml/, 'status cards must render their full detail immediately without an accordion click');
assert.match(html, /articleClass='zg-irl-entry'[\s\S]*?' status-card open'/, 'every status card must be visibly open by default');
assert.match(html, /meta=kind==='ability'\?[\s\S]*?:\[\]/, 'status duration must not be repeated as a second detail chip');
assert.match(html, /\.zg-irl-entry-description\{[^}]*font-size:16px/, 'full ability descriptions must use the larger readable type scale');
assert.match(html, /\.zg-irl-entry-copy strong\{[^}]*font-size:15px/, 'ability and status titles must use the larger readable type scale');
assert.match(html, /\.zg-irl-entry\.ability-card \.zg-irl-entry-copy strong\{[^}]*font-size:16\.5px/, 'visual ability cards must make their titles easier to scan');
assert.match(html, /\.zg-irl-rule-line\.tone-damage[\s\S]*?\.zg-irl-rule-line\.tone-healing[\s\S]*?\.zg-irl-rule-line\.tone-check[\s\S]*?\.zg-irl-rule-line\.tone-critical/, 'damage, healing, checks and critical outcomes must have visibly different color coding');
assert.match(html, /var IRL_GM_FOCUS=\{[\s\S]*?esteros:[\s\S]*?Колесо и погибшее животное[\s\S]*?Лупоглазик — свой[\s\S]*?Подсказка честная, не удобная/, 'Esteros must keep concise curated GM roleplay reminders');
assert.match(html, /var IRL_GM_FOCUS=\{[\s\S]*?'lin-yin':[\s\S]*?vrotik:[\s\S]*?evan:[\s\S]*?melissa:[\s\S]*?esteros:/, 'all five heroes must have curated GM focus collections');
assert.match(html, /Лин’Ин — ведьма[\s\S]*?Только чужими голосами[\s\S]*?Агра’рий — не Еван[\s\S]*?Видение осталось тайной/, 'each hero collection must surface its most useful roleplay anchor');
assert.match(html, /<small>Что сыграть сейчас<\/small>/, 'the GM column heading must state its practical purpose');
const gmFocusBlock = html.match(/var IRL_GM_FOCUS=\{[\s\S]*?\n  \};/);
assert.ok(gmFocusBlock, 'curated GM reminder source must exist');
const gmReminderTexts = [...gmFocusBlock[0].matchAll(/text:'([^']*)'/g)].map((match) => match[1]);
assert.strictEqual(gmReminderTexts.length, 20, 'all five heroes must keep four concise prompts each');
assert.ok(gmReminderTexts.every((text) => text.length <= 120), 'GM prompt prose must stay concise enough to scan without scrolling');
assert.match(html, /function irlGmFocusHtml\(heroKey,heroName\)[\s\S]*?zg-irl-gm-focus-grid[\s\S]*?tone-'\+esc\(item\.tone\)/, 'GM focus must render the semantic tone of each reminder');
assert.match(html, /w\.zgIrlCharacterHp=function\(key,delta\)[\s\S]*?state\.hpByKey\[key\]/, 'HP edits must be stored in the active IRL session');
const hpBlock = html.match(/w\.zgIrlCharacterHp=function\(key,delta\)[\s\S]*?\};/);
assert.ok(hpBlock, 'session HP handler must exist');
assert.doesNotMatch(hpBlock[0], /saveChars|persistCollection|ZargotaRooms/, 'IRL HP must not silently overwrite the canonical sheet or Firebase');
assert.match(html, /abilityUsageByKey=stored\.abilityUsageByKey[\s\S]*?sessionKey=String\(heroKey[\s\S]*?hasSession/, 'session cooldown overrides must be read separately from the canonical sheet');
assert.match(html, /function irlAbilityCooldownHtml\(item,heroKey\)[\s\S]*?zg-irl-charge-cell[\s\S]*?spent[\s\S]*?targetUsed/, 'expanded abilities must expose one direct clickable cell per charge');
assert.match(html, /\.zg-irl-entry\.ability-card \.zg-irl-cooldown-note\{[^}]*font-size:9\.5px/, 'secondary cooldown instructions must stay visually compact');
assert.match(html, /Зелёная — потратить, красная — вернуть\. Только для этой сессии\./, 'the cooldown hint must remain short enough to leave room for authored ability text');
assert.match(html, /zg-irl-cooldown-console'\+\(exhausted\?' exhausted'/, 'the whole cooldown console must enter the red exhausted state');
const cooldownBlock = html.match(/w\.zgIrlCharacterAbilityUsage=function\(heroKey,resourceKey,targetUsed\)[\s\S]*?\};/);
assert.ok(cooldownBlock, 'session cooldown handler must exist');
assert.match(cooldownBlock[0], /state\.abilityUsageByKey\[heroKey\+'\|'\+resourceKey\]=next/, 'cooldown edits must stay in the active IRL session');
assert.match(cooldownBlock[0], /Math\.min\(ability\.cdMax,Number\(targetUsed\)\|\|0\)/, 'a charge-cell click must set the exact spent-cell boundary');
assert.doesNotMatch(cooldownBlock[0], /saveChars|persistCollection|ZargotaRooms|abilityUsage\[/, 'IRL cooldown controls must not silently overwrite the canonical sheet or Firebase');
assert.match(html, /w\.zgIrlCharactersRefresh=function\(\)[\s\S]*?entry\.character\.hpCur[\s\S]*?state\.abilityUsageByKey=\{\}/, 'refresh must restore HP and cooldown values from the shared registry');
assert.match(html, /function innateActionKind\(card\)[\s\S]*?'short'[\s\S]*?'long'[\s\S]*?'passive'[\s\S]*?'reaction'[\s\S]*?'trait'/, 'the regular Characters section must classify innate cards by action type');
assert.match(html, /zg-spell-innate-card tone-'\+card\.tone\+' kind-'\+innateActionKind\(card\)/, 'regular character ability cards must receive their action color class');
assert.match(html, /\.zg-magic3 \.zg-spell-innate-card\.kind-short[\s\S]*?kind-long[\s\S]*?kind-passive[\s\S]*?kind-trait[\s\S]*?kind-reaction/, 'the regular Characters section must share the short, long, passive, trait and reaction palette');
assert.match(html, /function characterAbilityVisual\(item, field\)[\s\S]*?kind = 'reaction'[\s\S]*?kind = 'passive'[\s\S]*?kind = 'short'[\s\S]*?kind = 'long'[\s\S]*?kind = 'trait'/, 'the administrative Characters sheet must classify every authored ability row');
assert.match(html, /function characterAbilityRowHtml\(c, field, item, index[\s\S]*?data-character-ability-kind=[\s\S]*?openSkillCardPopup[\s\S]*?removeListItem/, 'colored registry rows must preserve their open and delete interactions');
assert.match(html, /function characterAbilityRowHtml\(c, field, item, index[\s\S]*?char-ability-charge-cell[\s\S]*?characterAbilitySetUsage/, 'registry rows must expose direct charge cells without opening the card');
assert.match(html, /window\.characterAbilitySetUsage = function\(charId, field, index, targetUsed\)[\s\S]*?item\.cdUsed = Math\.max/, 'registry charge cells must persist an exact spent-cell boundary');
assert.match(html, /function characterAbilityRuleSections\(text, item\)[\s\S]*?characterAbilityRuleLineKind[\s\S]*?sections\.filter/, 'the regular Characters popup must group authored lines into semantic sections');
assert.match(html, /function characterAbilityRulesHtml\(text, item\)[\s\S]*?char-ability-rule-section tone-[\s\S]*?characterAbilityRuleSectionBodyHtml/, 'semantic sections must escape and render their grouped rule text');
assert.match(html, /sc-ability-rules[^\n]*characterAbilityRulesHtml\(viewDescText, viewDisplayItem\)/, 'expanded registry abilities must render localized semantic rule markup instead of plain text');
assert.match(html, /function characterAbilityCleanDescription\(text, item\)[\s\S]*?item && item\.usages/, 'expanded ability text must remove repeated name, type and resource headings');
assert.match(html, /buildSkillsList\(c\)[\s\S]*?characterAbilityRowHtml\(c, 'skills'[\s\S]*?buildMasteryList\(c\)[\s\S]*?characterAbilityRowHtml\(c, 'mastery'/, 'both skills and mastery rows must use the shared visual renderer');
assert.match(html, /\.char-ability-row\.kind-short[\s\S]*?kind-long[\s\S]*?kind-passive[\s\S]*?kind-trait[\s\S]*?kind-reaction/, 'the administrative Characters sheet must use the same teal, amber, green, purple and coral palette');
assert.doesNotMatch(html.match(/<nav id="zg-irl-character-dock"[\s\S]*?<\/nav>/)[0], /onmouseenter|onmouseover/, 'hero cards must never open on hover');
assert.match(html, /\.zg-irl-character-layout\{flex:1;min-height:0;grid-template-columns:minmax\(340px,\.82fr\) minmax\(410px,1\.08fr\) minmax\(390px,1fr\)/, 'desktop composition must keep mechanics, abilities and GM roleplay visible in three columns');
assert.match(html, /\.zg-irl-ability-list\{flex:1;min-height:0;grid-auto-rows:max-content;overflow-y:auto/, 'long ability cards must keep their full height and scroll inside their own column');
assert.match(html, /\.zg-irl-status-list\{flex:0 0 auto;max-height:none[^}]*overflow:visible/, 'status cards must use their natural height instead of clipping inside a short scroller');
assert.match(html, /\.zg-irl-entry\.status-card \.zg-irl-entry-detail\{display:block/, 'status descriptions and rules must always be visible');
assert.match(html, /\.zg-irl-rule-lines\{display:block[^}]*background:#100c08/, 'ability rules must read as one calm block instead of a stack of colored cards');
assert.match(html, /\.zg-irl-gm-note h4\{[^}]*font-size:15\.5px\}/, 'GM reminder titles must remain readable at session distance');
assert.match(html, /\.zg-irl-gm-note p\{font-size:14\.5px;line-height:1\.5\}/, 'GM reminder prose must use the larger session-readable text scale');
const cardMarkup = html.match(/card\.innerHTML='<header class="zg-irl-character-head"[\s\S]*?';\n  \}/);
assert.ok(cardMarkup, 'expanded card markup must exist');
assert.match(cardMarkup[0], /zg-irl-character-mechanics[\s\S]*?>Характеристики<[\s\S]*?zg-irl-stats[\s\S]*?<\/section><section class="zg-irl-character-live">[\s\S]*?>Состояния<[\s\S]*?>Способности'\+abilityCountLabel/, 'portrait, HP and all characteristics must stay left while statuses and abilities stay right');
assert.match(cardMarkup[0], /<\/section>'\+irlGmFocusHtml\(selected\.key,name\)\+'<\/div>'/, 'roleplay guidance must remain a permanently visible third column');

console.log('IRL character dock: ok');
