const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const window={};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../story-outfits.js'),'utf8'),{window});
const api=window.ZargotaStoryOutfits,data={speakers:{hero:{emotions:{angry:{name:'Злой'},talk:{name:'Говорит'},joy:{name:'Радость'}}}},playerSpeakerId:'hero'};
api.install(data,'hero');api.install(data,'hero');
assert.equal(data.player.inventoryItems.length,1);
const result={portrait:'original.png'},node={speaker:'hero',emotion:'angry'};
assert.equal(api.resolve(data,node,null,result).portrait,'original.png');
const live=JSON.parse(JSON.stringify(data.player));live.inventoryItems[0].equipped=true;
assert(api.resolve(data,node,live,result).portrait.endsWith('03_angry.png'));
assert(api.tokenPortrait(data,live,'hero-token.png').endsWith('02_neutral.png'));
const unbound=JSON.parse(JSON.stringify(data));delete unbound.playerSpeakerId;
assert(api.tokenPortrait(unbound,live,'hero-token.png').endsWith('02_neutral.png'),'equipped cloak resolves even when the hero is not explicitly bound to a speaker');
assert(api.resolve(data,{speaker:'@player',emotion:'talk'},live,result).portrait.endsWith('05_speaking.png'));
assert(api.resolve(data,{speaker:'hero',emotion:'joy'},live,result).portrait.endsWith('02_neutral.png'));
assert.equal(api.resolve(data,{speaker:'other'},live,result).portrait,'original.png');
live.inventoryItems[0].equipped=false;
assert.equal(api.resolve(data,node,live,result).portrait,'original.png');
assert.equal(api.tokenPortrait(data,live,'hero-token.png'),'hero-token.png');
assert.equal(data.player.inventoryItems[0].equipped,false);
const playerSource=fs.readFileSync(path.join(__dirname,'../story-player.js'),'utf8');
assert.match(playerSource,/tokenPortrait\(data,state\.character,token\.image\)/,'hero token render uses the equipped portrait');
assert.match(playerSource,/function refreshHeroTokenPortrait\(\)/,'runtime equipment changes refresh the existing hero token');
assert.match(playerSource,/w\.ZargotaStoryHud\.apply\(root,data\);refreshHeroTokenPortrait\(\);/,'equipment refresh is tied to character state refresh');
console.log('PASS: preset, no duplicate item, dialogue and token runtime equip/unequip, fallback, other actor unaffected');
