const assert=require('node:assert/strict'),rules=require('../story-card-game-core.js');
let serial=0;const card=rank=>({id:'fixture-'+serial++,rank,color:serial%2});
const g=rules.create({players:3,stacks:[5,10,20]});
g.players[0].hand=[card(2),card(2)];g.players[1].hand=[card(1),card(1)];g.players[2].hand=[card(9),card(10)];
g.deck=[1,1,2,2,3,4].map(card).reverse();
assert(rules.act(g,'allin'));assert(!g.players[0].folded);
assert.equal(rules.raiseLimit(g),5,'short all-in does not cap the next player');
assert(rules.act(g,'allin'));assert(rules.act(g,'call'));assert(g.done);
assert.deepEqual(g.payouts,[15,10,0]);assert.deepEqual(g.players.map(p=>p.stack),[15,10,10]);
assert.deepEqual(g.pots.map(p=>p.amount),[15,10]);assert.equal(g.paid,25);
const h=rules.create({players:3,stacks:[20,5,10]});
assert(rules.act(h,'allin'));assert(rules.act(h,'call'));assert(rules.act(h,'call'));
assert(h.done);assert(!h.pots.some(p=>p.refund),'uncovered excess stays in the wallet');
assert.equal(h.players.reduce((sum,p)=>sum+p.stack,0),35);
assert(h.pots.filter(p=>!p.refund).every(p=>p.winners.every(i=>!h.players[i].folded)));
const zero=rules.create({stacks:[15,0,21,0]});assert.equal(rules.raiseLimit(zero),15);assert(rules.legal(zero).includes('allin'));
console.log('All-in: zero stacks, short calls, main/side winners, refunds and conservation passed.');
const capped=rules.create({stacks:[60,12,21,0]});
assert.equal(rules.raiseLimit(capped),21);
assert.equal(rules.act(capped,'raise',22),false,'manual amount cannot bypass coverage');
assert(rules.act(capped,'allin'));assert.equal(capped.players[0].stack,39);assert.equal(capped.target,21);
const prior=rules.create({stacks:[50,20,90,0]});
prior.players[0].bet=3;prior.players[0].contributed=8;
prior.players[1].bet=7;prior.players[1].contributed=12;
prior.players[2].folded=true;prior.target=7;
assert.equal(rules.raiseLimit(prior),20,'includes previous contributions, excludes folded rich players');
assert(rules.act(prior,'allin'));assert.equal(prior.players[0].lastBet.added,24);assert.equal(prior.players[0].stack,26);
