'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const context={window:{}};
vm.createContext(context);
for(const file of ['story-campaign.js','story-player.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),context);
const project=context.window.ZargotaStoryCampaign;
const rules=context.window.ZargotaStoryRules;
const playerCss=fs.readFileSync(path.join(__dirname,'..','story-player.css'),'utf8');
const ids=new Set(project.nodes.map(n=>n.id));
for(const node of project.nodes){
  assert(node.text&&node.textUk,'Every authored line has both locales');
  assert(project.speakers[node.speaker],'Speaker resolves to portrait metadata');
  for(const link of node.links){assert(ids.has(link.to),'Every dialogue edge resolves');if(link.label)assert(link.labelUk,'Every choice has both locales');}
}
const run=rules.createState(project);
assert.equal(rules.choose(project,run,'dialog-1','missing'),null);
assert.equal(run.choice,null,'Invalid choice does not change state');
assert.equal(rules.choose(project,run,'dialog-1','line-1').to,'dialog-2');
const stay=rules.choose(project,run,'dialog-3','line-3');
assert.equal(stay.to,'dialog-stay');assert.equal(stay.delayMs,450);assert.equal(run.choice,'stay');
const second=rules.createState(project);
assert.equal(second.choice,null,'Replay clears previous choice');
assert.equal(second.completed,false,'Replay clears completion');
assert.equal(rules.choose(project,second,'dialog-3','line-4').to,'dialog-go');
assert.equal(second.choice,'together');assert.equal(run.choice,'stay','Runs are isolated');
const broken=JSON.parse(JSON.stringify(project));broken.nodes=broken.nodes.filter(n=>n.id!=='dialog-stay');
assert.equal(rules.choose(broken,rules.createState(broken),'dialog-3','line-3'),null,'Deleted targets do not crash playback');
const concave=[[0,0],[100,0],[100,30],[30,30],[30,100],[0,100]];
assert(rules.pathAllowed({x:10,y:10},{x:10,y:90},concave));
assert(!rules.pathAllowed({x:10,y:90},{x:90,y:10},concave),'Movement cannot cross forbidden space even with valid endpoints');
assert(!rules.pathAllowed({x:10,y:10},{x:80,y:80},concave));
assert(rules.pathAllowed({x:10,y:10},{x:10,y:10},concave));
assert.equal(project.nodes.filter(n=>n.links.length>1).length,1,'Demo has exactly one branching choice');
assert.match(playerCss,/button\.zg-story-play-token:hover:not\(:disabled\),\.zg-story-player button\.zg-story-play-token:active:not\(:disabled\)\{transform:translate\(-50%,-50%\)\}/,'Hover and active states keep story targets anchored');
assert.match(playerCss,/\.zg-story-dialogue\{[^}]*background:transparent/,'Dialogue remains transparent over the map');
assert.match(playerCss,/\.zg-story-speaker-frame\{[^}]*mask-image:radial-gradient\(circle/,'Portrait uses a feathered circular transparency mask');
console.log('Story playback rules, bilingual graph, reset and movement boundaries passed');
const conditional=JSON.parse(JSON.stringify(project));
conditional.nodes[0].links[0].requires='stone_examined';
const conditionalRun=rules.createState(conditional);
assert.equal(rules.choose(conditional,conditionalRun,'dialog-1','line-1'),null);
conditionalRun.flags.stone_examined=true;
conditional.nodes[0].links[0].effect='brother_trust';
assert.equal(rules.choose(conditional,conditionalRun,'dialog-1','line-1').to,'dialog-2');
assert.equal(conditionalRun.flags.brother_trust,true);
assert.equal(rules.createState(conditional).flags.brother_trust,undefined);
const travel=JSON.parse(JSON.stringify(project));
travel.scenes=[{id:'next-scene',scene:{}}];
travel.nodes[0].links=[{id:'travel',to:'',sceneId:'next-scene',effect:'arrived'}];
assert.equal(rules.choose(travel,rules.createState(travel),'dialog-1','travel').sceneId,'next-scene');
travel.nodes[0].links[0].sceneId='deleted-scene';
const invalidRun=rules.createState(travel);
assert.equal(rules.choose(travel,invalidRun,'dialog-1','travel'),null);
assert.equal(invalidRun.flags.arrived,undefined,'invalid scene cannot apply consequences');
