const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');const w={},ctx={window:w};vm.createContext(ctx);
for(const file of ['story-card-economy.js','story-card-game-core.js','story-items.js','story-player.js'])vm.runInContext(fs.readFileSync(file,'utf8'),ctx);
const project=JSON.parse(fs.readFileSync('story-content/evan/episode-1-courtyard-v21.json')).episode,c=project.minigames.towerClaw,ids=[project.playerSpeakerId,...c.opponents],api=w.ZargotaCardEconomy;
function run(n=10){return {flags:{},character:{inventoryItems:[{itemId:'evan-copper-coin',qty:n},{itemId:'evan-silver-coin',qty:5}]}};}
let state=run(),wallet=api.begin(project,state);assert.equal(JSON.stringify(wallet.stacks),JSON.stringify([10,10,6,7]));assert.equal(api.count(state.character,'evan-copper-coin'),0);assert.equal(api.count(state.character,'evan-silver-coin'),5);assert.equal(api.begin(project,state),null);
const game=w.ZargotaCardRules.create({players:4,stacks:wallet.stacks});w.ZargotaCardRules.act(game,'raise',2);wallet.finish(game,ids);assert.equal(api.count(state.character,'evan-copper-coin'),10);assert.equal(state.cardWallets.players[ids[1]],4);assert.equal(state.cardWallets.sponsorReturn,6);wallet.finish(game,ids);assert.equal(api.count(state.character,'evan-copper-coin'),10);
wallet=api.begin(project,state);assert.equal(wallet.stacks[1],4);wallet.finish(null,ids);
state=run(30);wallet=api.begin(project,state);const soldGame={done:true,players:[{stack:37},{stack:10},{stack:6},{stack:0}]};assert.equal(wallet.sell(soldGame,ids,ids[3]),true);assert.equal(soldGame.players[0].stack,32);assert.equal(soldGame.players[3].stack,5);assert.equal(api.count(state.character,'evan-broken-counter'),1);assert.equal(wallet.sell(soldGame,ids,ids[3]),false);wallet.finish(soldGame,ids);assert.equal(api.count(state.character,'evan-copper-coin'),32);assert.equal(api.begin(project,state).stacks[3],5);
state=run(10);wallet=api.begin(project,state);wallet.finish({done:true,players:[{stack:5},{stack:20},{stack:3},{stack:5}]},ids);assert.equal(state.cardWallets.sponsorReturn,11);assert.equal(state.cardWallets.players[ids[1]],9);
state=run(10);wallet=api.begin(project,state);wallet.finish({done:true,players:[{stack:10},{stack:5},{stack:8},{stack:10}]},ids);assert.equal(state.cardWallets.sponsorReturn,3);assert.equal(state.cardWallets.players[ids[1]],2);
assert.equal(api.begin(project,run(0)),null);assert.match(api.format('{{silver}} / {{copper}} / {{lidaContribution}}',project,run()),/^5 \/ 10 \/ 6$/);
const s=run(0),rules=w.ZargotaStoryRules;const enter=project.nodes.find(n=>n.id==='evan-port-stake');const paid=enter.links.find(l=>l.requiresItemId==='evan-copper-coin');assert.equal(rules.choose(project,s,enter.id,paid.id),null);
// Cross-check the real core over many complete rounds: cash is conserved after sponsor settlement.
for(let seed=1;seed<=100;seed++){let rand=seed;const random=()=>((rand=(rand*1664525+1013904223)>>>0)/4294967296),s=run(10),b=api.begin(project,s),g=w.ZargotaCardRules.create({players:4,stacks:b.stacks},random);let turns=0;while(!g.done&&turns++<300){const action=w.ZargotaCardRules.npc(g,random,'balanced');w.ZargotaCardRules.act(g,action,action==='raise'?1:undefined);}assert.ok(g.done);b.finish(g,ids);const total=api.count(s.character,'evan-copper-coin')+Object.values(s.cardWallets.players).reduce((n,v)=>n+v,0)+s.cardWallets.sponsorReturn;assert.equal(total,33);}
console.log('Paid cards: escrow, repeat visits, abort refund, silver preservation, item transfer, sponsor profit/loss and 100 conserved games passed.');
