const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const context={window:{ZargotaEquipmentRules:require('../equipment-rules.js')}};
vm.runInNewContext(fs.readFileSync('story-actors.js','utf8'),context);
vm.runInNewContext(fs.readFileSync('story-player.js','utf8'),context);
const actors=context.window.ZargotaStoryActors;
const data={heroTokenId:'custom',scene:{tokens:[{id:'custom',name:'Custom hero',image:'hero.png'}]},speakers:{npc:{name:'NPC',portrait:'normal.png',position:'50% 30%',zoom:1.2,emotions:{angry:{portrait:'angry.png',zoom:1}}}},player:{hp:12,hpMax:12,ac:10,stats:{str:3},inventoryItems:[{itemId:'shield',name:'Shield',category:'shield',acBonus:2},{itemId:'potion',name:'Potion',category:'consumable',qty:2}]}};
assert.equal(actors.portrait(data,{speaker:'npc',emotion:'angry'}).portrait,'angry.png');
assert.equal(actors.portrait(data,{speaker:'npc'}).portrait,'normal.png');
assert.equal(actors.portrait(data,{speaker:'npc',emotion:'deleted'}).portrait,'normal.png');
assert.equal(actors.portrait(data,{speaker:'npc',emotion:'angry',portrait:'override.png'}).portrait,'override.png');
const hero=actors.character(data);
assert.equal(hero.name,'Custom hero');
const equip=actors.mutate(hero,{action:'equip',index:0});
assert.equal(equip.ok,true);assert.equal(equip.source.ac,12);
assert.equal(hero.ac,10);assert.equal(data.player.inventoryItems[0].equipped,undefined,'project unchanged');
const unequip=actors.mutate(equip.source,{action:'equip',index:0});
assert.equal(unequip.source.ac,10,'equipment bonus removed without stacking');
const used=actors.mutate(hero,{action:'use',index:1});
assert.equal(used.source.inventoryItems[1].qty,1);
assert.equal(data.player.inventoryItems[1].qty,2,'starting inventory untouched');
const first=context.window.ZargotaStoryRules.createState(data),second=context.window.ZargotaStoryRules.createState(data);
first.character.inventoryItems.pop();assert.equal(second.character.inventoryItems.length,2,'restart isolation');
console.log('Story actors: optional portraits, fallback, custom hero, shared inventory equipment/use and isolated restart passed');
